// Code generated by ent, DO NOT EDIT.

package subscriptionplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the subscriptionplan type in the database.
	Label = "subscription_plan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldTierCode holds the string denoting the tier_code field in the database.
	FieldTierCode = "tier_code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldOriginalPrice holds the string denoting the original_price field in the database.
	FieldOriginalPrice = "original_price"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldValidityDays holds the string denoting the validity_days field in the database.
	FieldValidityDays = "validity_days"
	// FieldValidityUnit holds the string denoting the validity_unit field in the database.
	FieldValidityUnit = "validity_unit"
	// FieldFeatures holds the string denoting the features field in the database.
	FieldFeatures = "features"
	// FieldProductName holds the string denoting the product_name field in the database.
	FieldProductName = "product_name"
	// FieldForSale holds the string denoting the for_sale field in the database.
	FieldForSale = "for_sale"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldConcurrencyEntitlement holds the string denoting the concurrency_entitlement field in the database.
	FieldConcurrencyEntitlement = "concurrency_entitlement"
	// FieldLifetimeQuotaUsd holds the string denoting the lifetime_quota_usd field in the database.
	FieldLifetimeQuotaUsd = "lifetime_quota_usd"
	// FieldDailyQuotaUsd holds the string denoting the daily_quota_usd field in the database.
	FieldDailyQuotaUsd = "daily_quota_usd"
	// FieldWeeklyQuotaUsd holds the string denoting the weekly_quota_usd field in the database.
	FieldWeeklyQuotaUsd = "weekly_quota_usd"
	// FieldMonthlyQuotaUsd holds the string denoting the monthly_quota_usd field in the database.
	FieldMonthlyQuotaUsd = "monthly_quota_usd"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeGroups holds the string denoting the groups edge name in mutations.
	EdgeGroups = "groups"
	// Table holds the table name of the subscriptionplan in the database.
	Table = "subscription_plans"
	// GroupsTable is the table that holds the groups relation/edge.
	GroupsTable = "subscription_plan_groups"
	// GroupsInverseTable is the table name for the SubscriptionPlanGroup entity.
	// It exists in this package in order to avoid circular dependency with the "subscriptionplangroup" package.
	GroupsInverseTable = "subscription_plan_groups"
	// GroupsColumn is the table column denoting the groups relation/edge.
	GroupsColumn = "plan_id"
)

// Columns holds all SQL columns for subscriptionplan fields.
var Columns = []string{
	FieldID,
	FieldGroupID,
	FieldTierCode,
	FieldName,
	FieldDescription,
	FieldPrice,
	FieldOriginalPrice,
	FieldCurrency,
	FieldValidityDays,
	FieldValidityUnit,
	FieldFeatures,
	FieldProductName,
	FieldForSale,
	FieldSortOrder,
	FieldConcurrencyEntitlement,
	FieldLifetimeQuotaUsd,
	FieldDailyQuotaUsd,
	FieldWeeklyQuotaUsd,
	FieldMonthlyQuotaUsd,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTierCode holds the default value on creation for the "tier_code" field.
	DefaultTierCode string
	// TierCodeValidator is a validator for the "tier_code" field. It is called by the builders before save.
	TierCodeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultValidityDays holds the default value on creation for the "validity_days" field.
	DefaultValidityDays int
	// DefaultValidityUnit holds the default value on creation for the "validity_unit" field.
	DefaultValidityUnit string
	// ValidityUnitValidator is a validator for the "validity_unit" field. It is called by the builders before save.
	ValidityUnitValidator func(string) error
	// DefaultFeatures holds the default value on creation for the "features" field.
	DefaultFeatures string
	// DefaultProductName holds the default value on creation for the "product_name" field.
	DefaultProductName string
	// ProductNameValidator is a validator for the "product_name" field. It is called by the builders before save.
	ProductNameValidator func(string) error
	// DefaultForSale holds the default value on creation for the "for_sale" field.
	DefaultForSale bool
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultConcurrencyEntitlement holds the default value on creation for the "concurrency_entitlement" field.
	DefaultConcurrencyEntitlement int
	// DefaultLifetimeQuotaUsd holds the default value on creation for the "lifetime_quota_usd" field.
	DefaultLifetimeQuotaUsd float64
	// DefaultDailyQuotaUsd holds the default value on creation for the "daily_quota_usd" field.
	DefaultDailyQuotaUsd float64
	// DefaultWeeklyQuotaUsd holds the default value on creation for the "weekly_quota_usd" field.
	DefaultWeeklyQuotaUsd float64
	// DefaultMonthlyQuotaUsd holds the default value on creation for the "monthly_quota_usd" field.
	DefaultMonthlyQuotaUsd float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the SubscriptionPlan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByTierCode orders the results by the tier_code field.
func ByTierCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTierCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByOriginalPrice orders the results by the original_price field.
func ByOriginalPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalPrice, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByValidityDays orders the results by the validity_days field.
func ByValidityDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidityDays, opts...).ToFunc()
}

// ByValidityUnit orders the results by the validity_unit field.
func ByValidityUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidityUnit, opts...).ToFunc()
}

// ByFeatures orders the results by the features field.
func ByFeatures(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeatures, opts...).ToFunc()
}

// ByProductName orders the results by the product_name field.
func ByProductName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductName, opts...).ToFunc()
}

// ByForSale orders the results by the for_sale field.
func ByForSale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForSale, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByConcurrencyEntitlement orders the results by the concurrency_entitlement field.
func ByConcurrencyEntitlement(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConcurrencyEntitlement, opts...).ToFunc()
}

// ByLifetimeQuotaUsd orders the results by the lifetime_quota_usd field.
func ByLifetimeQuotaUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLifetimeQuotaUsd, opts...).ToFunc()
}

// ByDailyQuotaUsd orders the results by the daily_quota_usd field.
func ByDailyQuotaUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyQuotaUsd, opts...).ToFunc()
}

// ByWeeklyQuotaUsd orders the results by the weekly_quota_usd field.
func ByWeeklyQuotaUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyQuotaUsd, opts...).ToFunc()
}

// ByMonthlyQuotaUsd orders the results by the monthly_quota_usd field.
func ByMonthlyQuotaUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyQuotaUsd, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGroupsCount orders the results by groups count.
func ByGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGroupsStep(), opts...)
	}
}

// ByGroups orders the results by groups terms.
func ByGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GroupsTable, GroupsColumn),
	)
}
