// Code generated by ent, DO NOT EDIT.

package subscriptionplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldID, id))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldGroupID, v))
}

// TierCode applies equality check predicate on the "tier_code" field. It's identical to TierCodeEQ.
func TierCode(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldTierCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldDescription, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldPrice, v))
}

// OriginalPrice applies equality check predicate on the "original_price" field. It's identical to OriginalPriceEQ.
func OriginalPrice(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldOriginalPrice, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldCurrency, v))
}

// ValidityDays applies equality check predicate on the "validity_days" field. It's identical to ValidityDaysEQ.
func ValidityDays(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityUnit applies equality check predicate on the "validity_unit" field. It's identical to ValidityUnitEQ.
func ValidityUnit(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldValidityUnit, v))
}

// Features applies equality check predicate on the "features" field. It's identical to FeaturesEQ.
func Features(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldFeatures, v))
}

// ProductName applies equality check predicate on the "product_name" field. It's identical to ProductNameEQ.
func ProductName(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldProductName, v))
}

// ForSale applies equality check predicate on the "for_sale" field. It's identical to ForSaleEQ.
func ForSale(v bool) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldForSale, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldSortOrder, v))
}

// ConcurrencyEntitlement applies equality check predicate on the "concurrency_entitlement" field. It's identical to ConcurrencyEntitlementEQ.
func ConcurrencyEntitlement(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldConcurrencyEntitlement, v))
}

// LifetimeQuotaUsd applies equality check predicate on the "lifetime_quota_usd" field. It's identical to LifetimeQuotaUsdEQ.
func LifetimeQuotaUsd(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldLifetimeQuotaUsd, v))
}

// DailyQuotaUsd applies equality check predicate on the "daily_quota_usd" field. It's identical to DailyQuotaUsdEQ.
func DailyQuotaUsd(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldDailyQuotaUsd, v))
}

// WeeklyQuotaUsd applies equality check predicate on the "weekly_quota_usd" field. It's identical to WeeklyQuotaUsdEQ.
func WeeklyQuotaUsd(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldWeeklyQuotaUsd, v))
}

// MonthlyQuotaUsd applies equality check predicate on the "monthly_quota_usd" field. It's identical to MonthlyQuotaUsdEQ.
func MonthlyQuotaUsd(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldMonthlyQuotaUsd, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldGroupID, v))
}

// TierCodeEQ applies the EQ predicate on the "tier_code" field.
func TierCodeEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldTierCode, v))
}

// TierCodeNEQ applies the NEQ predicate on the "tier_code" field.
func TierCodeNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldTierCode, v))
}

// TierCodeIn applies the In predicate on the "tier_code" field.
func TierCodeIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldTierCode, vs...))
}

// TierCodeNotIn applies the NotIn predicate on the "tier_code" field.
func TierCodeNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldTierCode, vs...))
}

// TierCodeGT applies the GT predicate on the "tier_code" field.
func TierCodeGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldTierCode, v))
}

// TierCodeGTE applies the GTE predicate on the "tier_code" field.
func TierCodeGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldTierCode, v))
}

// TierCodeLT applies the LT predicate on the "tier_code" field.
func TierCodeLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldTierCode, v))
}

// TierCodeLTE applies the LTE predicate on the "tier_code" field.
func TierCodeLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldTierCode, v))
}

// TierCodeContains applies the Contains predicate on the "tier_code" field.
func TierCodeContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldTierCode, v))
}

// TierCodeHasPrefix applies the HasPrefix predicate on the "tier_code" field.
func TierCodeHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldTierCode, v))
}

// TierCodeHasSuffix applies the HasSuffix predicate on the "tier_code" field.
func TierCodeHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldTierCode, v))
}

// TierCodeEqualFold applies the EqualFold predicate on the "tier_code" field.
func TierCodeEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldTierCode, v))
}

// TierCodeContainsFold applies the ContainsFold predicate on the "tier_code" field.
func TierCodeContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldTierCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldDescription, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldPrice, v))
}

// OriginalPriceEQ applies the EQ predicate on the "original_price" field.
func OriginalPriceEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldOriginalPrice, v))
}

// OriginalPriceNEQ applies the NEQ predicate on the "original_price" field.
func OriginalPriceNEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldOriginalPrice, v))
}

// OriginalPriceIn applies the In predicate on the "original_price" field.
func OriginalPriceIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldOriginalPrice, vs...))
}

// OriginalPriceNotIn applies the NotIn predicate on the "original_price" field.
func OriginalPriceNotIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldOriginalPrice, vs...))
}

// OriginalPriceGT applies the GT predicate on the "original_price" field.
func OriginalPriceGT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldOriginalPrice, v))
}

// OriginalPriceGTE applies the GTE predicate on the "original_price" field.
func OriginalPriceGTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldOriginalPrice, v))
}

// OriginalPriceLT applies the LT predicate on the "original_price" field.
func OriginalPriceLT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldOriginalPrice, v))
}

// OriginalPriceLTE applies the LTE predicate on the "original_price" field.
func OriginalPriceLTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldOriginalPrice, v))
}

// OriginalPriceIsNil applies the IsNil predicate on the "original_price" field.
func OriginalPriceIsNil() predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIsNull(FieldOriginalPrice))
}

// OriginalPriceNotNil applies the NotNil predicate on the "original_price" field.
func OriginalPriceNotNil() predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotNull(FieldOriginalPrice))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldCurrency, v))
}

// ValidityDaysEQ applies the EQ predicate on the "validity_days" field.
func ValidityDaysEQ(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityDaysNEQ applies the NEQ predicate on the "validity_days" field.
func ValidityDaysNEQ(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldValidityDays, v))
}

// ValidityDaysIn applies the In predicate on the "validity_days" field.
func ValidityDaysIn(vs ...int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldValidityDays, vs...))
}

// ValidityDaysNotIn applies the NotIn predicate on the "validity_days" field.
func ValidityDaysNotIn(vs ...int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldValidityDays, vs...))
}

// ValidityDaysGT applies the GT predicate on the "validity_days" field.
func ValidityDaysGT(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldValidityDays, v))
}

// ValidityDaysGTE applies the GTE predicate on the "validity_days" field.
func ValidityDaysGTE(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldValidityDays, v))
}

// ValidityDaysLT applies the LT predicate on the "validity_days" field.
func ValidityDaysLT(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldValidityDays, v))
}

// ValidityDaysLTE applies the LTE predicate on the "validity_days" field.
func ValidityDaysLTE(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldValidityDays, v))
}

// ValidityUnitEQ applies the EQ predicate on the "validity_unit" field.
func ValidityUnitEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldValidityUnit, v))
}

// ValidityUnitNEQ applies the NEQ predicate on the "validity_unit" field.
func ValidityUnitNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldValidityUnit, v))
}

// ValidityUnitIn applies the In predicate on the "validity_unit" field.
func ValidityUnitIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldValidityUnit, vs...))
}

// ValidityUnitNotIn applies the NotIn predicate on the "validity_unit" field.
func ValidityUnitNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldValidityUnit, vs...))
}

// ValidityUnitGT applies the GT predicate on the "validity_unit" field.
func ValidityUnitGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldValidityUnit, v))
}

// ValidityUnitGTE applies the GTE predicate on the "validity_unit" field.
func ValidityUnitGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldValidityUnit, v))
}

// ValidityUnitLT applies the LT predicate on the "validity_unit" field.
func ValidityUnitLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldValidityUnit, v))
}

// ValidityUnitLTE applies the LTE predicate on the "validity_unit" field.
func ValidityUnitLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldValidityUnit, v))
}

// ValidityUnitContains applies the Contains predicate on the "validity_unit" field.
func ValidityUnitContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldValidityUnit, v))
}

// ValidityUnitHasPrefix applies the HasPrefix predicate on the "validity_unit" field.
func ValidityUnitHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldValidityUnit, v))
}

// ValidityUnitHasSuffix applies the HasSuffix predicate on the "validity_unit" field.
func ValidityUnitHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldValidityUnit, v))
}

// ValidityUnitEqualFold applies the EqualFold predicate on the "validity_unit" field.
func ValidityUnitEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldValidityUnit, v))
}

// ValidityUnitContainsFold applies the ContainsFold predicate on the "validity_unit" field.
func ValidityUnitContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldValidityUnit, v))
}

// FeaturesEQ applies the EQ predicate on the "features" field.
func FeaturesEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldFeatures, v))
}

// FeaturesNEQ applies the NEQ predicate on the "features" field.
func FeaturesNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldFeatures, v))
}

// FeaturesIn applies the In predicate on the "features" field.
func FeaturesIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldFeatures, vs...))
}

// FeaturesNotIn applies the NotIn predicate on the "features" field.
func FeaturesNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldFeatures, vs...))
}

// FeaturesGT applies the GT predicate on the "features" field.
func FeaturesGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldFeatures, v))
}

// FeaturesGTE applies the GTE predicate on the "features" field.
func FeaturesGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldFeatures, v))
}

// FeaturesLT applies the LT predicate on the "features" field.
func FeaturesLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldFeatures, v))
}

// FeaturesLTE applies the LTE predicate on the "features" field.
func FeaturesLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldFeatures, v))
}

// FeaturesContains applies the Contains predicate on the "features" field.
func FeaturesContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldFeatures, v))
}

// FeaturesHasPrefix applies the HasPrefix predicate on the "features" field.
func FeaturesHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldFeatures, v))
}

// FeaturesHasSuffix applies the HasSuffix predicate on the "features" field.
func FeaturesHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldFeatures, v))
}

// FeaturesEqualFold applies the EqualFold predicate on the "features" field.
func FeaturesEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldFeatures, v))
}

// FeaturesContainsFold applies the ContainsFold predicate on the "features" field.
func FeaturesContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldFeatures, v))
}

// ProductNameEQ applies the EQ predicate on the "product_name" field.
func ProductNameEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldProductName, v))
}

// ProductNameNEQ applies the NEQ predicate on the "product_name" field.
func ProductNameNEQ(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldProductName, v))
}

// ProductNameIn applies the In predicate on the "product_name" field.
func ProductNameIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldProductName, vs...))
}

// ProductNameNotIn applies the NotIn predicate on the "product_name" field.
func ProductNameNotIn(vs ...string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldProductName, vs...))
}

// ProductNameGT applies the GT predicate on the "product_name" field.
func ProductNameGT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldProductName, v))
}

// ProductNameGTE applies the GTE predicate on the "product_name" field.
func ProductNameGTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldProductName, v))
}

// ProductNameLT applies the LT predicate on the "product_name" field.
func ProductNameLT(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldProductName, v))
}

// ProductNameLTE applies the LTE predicate on the "product_name" field.
func ProductNameLTE(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldProductName, v))
}

// ProductNameContains applies the Contains predicate on the "product_name" field.
func ProductNameContains(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContains(FieldProductName, v))
}

// ProductNameHasPrefix applies the HasPrefix predicate on the "product_name" field.
func ProductNameHasPrefix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasPrefix(FieldProductName, v))
}

// ProductNameHasSuffix applies the HasSuffix predicate on the "product_name" field.
func ProductNameHasSuffix(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldHasSuffix(FieldProductName, v))
}

// ProductNameEqualFold applies the EqualFold predicate on the "product_name" field.
func ProductNameEqualFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEqualFold(FieldProductName, v))
}

// ProductNameContainsFold applies the ContainsFold predicate on the "product_name" field.
func ProductNameContainsFold(v string) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldContainsFold(FieldProductName, v))
}

// ForSaleEQ applies the EQ predicate on the "for_sale" field.
func ForSaleEQ(v bool) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldForSale, v))
}

// ForSaleNEQ applies the NEQ predicate on the "for_sale" field.
func ForSaleNEQ(v bool) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldForSale, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldSortOrder, v))
}

// ConcurrencyEntitlementEQ applies the EQ predicate on the "concurrency_entitlement" field.
func ConcurrencyEntitlementEQ(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldConcurrencyEntitlement, v))
}

// ConcurrencyEntitlementNEQ applies the NEQ predicate on the "concurrency_entitlement" field.
func ConcurrencyEntitlementNEQ(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldConcurrencyEntitlement, v))
}

// ConcurrencyEntitlementIn applies the In predicate on the "concurrency_entitlement" field.
func ConcurrencyEntitlementIn(vs ...int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldConcurrencyEntitlement, vs...))
}

// ConcurrencyEntitlementNotIn applies the NotIn predicate on the "concurrency_entitlement" field.
func ConcurrencyEntitlementNotIn(vs ...int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldConcurrencyEntitlement, vs...))
}

// ConcurrencyEntitlementGT applies the GT predicate on the "concurrency_entitlement" field.
func ConcurrencyEntitlementGT(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldConcurrencyEntitlement, v))
}

// ConcurrencyEntitlementGTE applies the GTE predicate on the "concurrency_entitlement" field.
func ConcurrencyEntitlementGTE(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldConcurrencyEntitlement, v))
}

// ConcurrencyEntitlementLT applies the LT predicate on the "concurrency_entitlement" field.
func ConcurrencyEntitlementLT(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldConcurrencyEntitlement, v))
}

// ConcurrencyEntitlementLTE applies the LTE predicate on the "concurrency_entitlement" field.
func ConcurrencyEntitlementLTE(v int) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldConcurrencyEntitlement, v))
}

// LifetimeQuotaUsdEQ applies the EQ predicate on the "lifetime_quota_usd" field.
func LifetimeQuotaUsdEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldLifetimeQuotaUsd, v))
}

// LifetimeQuotaUsdNEQ applies the NEQ predicate on the "lifetime_quota_usd" field.
func LifetimeQuotaUsdNEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldLifetimeQuotaUsd, v))
}

// LifetimeQuotaUsdIn applies the In predicate on the "lifetime_quota_usd" field.
func LifetimeQuotaUsdIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldLifetimeQuotaUsd, vs...))
}

// LifetimeQuotaUsdNotIn applies the NotIn predicate on the "lifetime_quota_usd" field.
func LifetimeQuotaUsdNotIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldLifetimeQuotaUsd, vs...))
}

// LifetimeQuotaUsdGT applies the GT predicate on the "lifetime_quota_usd" field.
func LifetimeQuotaUsdGT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldLifetimeQuotaUsd, v))
}

// LifetimeQuotaUsdGTE applies the GTE predicate on the "lifetime_quota_usd" field.
func LifetimeQuotaUsdGTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldLifetimeQuotaUsd, v))
}

// LifetimeQuotaUsdLT applies the LT predicate on the "lifetime_quota_usd" field.
func LifetimeQuotaUsdLT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldLifetimeQuotaUsd, v))
}

// LifetimeQuotaUsdLTE applies the LTE predicate on the "lifetime_quota_usd" field.
func LifetimeQuotaUsdLTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldLifetimeQuotaUsd, v))
}

// DailyQuotaUsdEQ applies the EQ predicate on the "daily_quota_usd" field.
func DailyQuotaUsdEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldDailyQuotaUsd, v))
}

// DailyQuotaUsdNEQ applies the NEQ predicate on the "daily_quota_usd" field.
func DailyQuotaUsdNEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldDailyQuotaUsd, v))
}

// DailyQuotaUsdIn applies the In predicate on the "daily_quota_usd" field.
func DailyQuotaUsdIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldDailyQuotaUsd, vs...))
}

// DailyQuotaUsdNotIn applies the NotIn predicate on the "daily_quota_usd" field.
func DailyQuotaUsdNotIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldDailyQuotaUsd, vs...))
}

// DailyQuotaUsdGT applies the GT predicate on the "daily_quota_usd" field.
func DailyQuotaUsdGT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldDailyQuotaUsd, v))
}

// DailyQuotaUsdGTE applies the GTE predicate on the "daily_quota_usd" field.
func DailyQuotaUsdGTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldDailyQuotaUsd, v))
}

// DailyQuotaUsdLT applies the LT predicate on the "daily_quota_usd" field.
func DailyQuotaUsdLT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldDailyQuotaUsd, v))
}

// DailyQuotaUsdLTE applies the LTE predicate on the "daily_quota_usd" field.
func DailyQuotaUsdLTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldDailyQuotaUsd, v))
}

// WeeklyQuotaUsdEQ applies the EQ predicate on the "weekly_quota_usd" field.
func WeeklyQuotaUsdEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldWeeklyQuotaUsd, v))
}

// WeeklyQuotaUsdNEQ applies the NEQ predicate on the "weekly_quota_usd" field.
func WeeklyQuotaUsdNEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldWeeklyQuotaUsd, v))
}

// WeeklyQuotaUsdIn applies the In predicate on the "weekly_quota_usd" field.
func WeeklyQuotaUsdIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldWeeklyQuotaUsd, vs...))
}

// WeeklyQuotaUsdNotIn applies the NotIn predicate on the "weekly_quota_usd" field.
func WeeklyQuotaUsdNotIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldWeeklyQuotaUsd, vs...))
}

// WeeklyQuotaUsdGT applies the GT predicate on the "weekly_quota_usd" field.
func WeeklyQuotaUsdGT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldWeeklyQuotaUsd, v))
}

// WeeklyQuotaUsdGTE applies the GTE predicate on the "weekly_quota_usd" field.
func WeeklyQuotaUsdGTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldWeeklyQuotaUsd, v))
}

// WeeklyQuotaUsdLT applies the LT predicate on the "weekly_quota_usd" field.
func WeeklyQuotaUsdLT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldWeeklyQuotaUsd, v))
}

// WeeklyQuotaUsdLTE applies the LTE predicate on the "weekly_quota_usd" field.
func WeeklyQuotaUsdLTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldWeeklyQuotaUsd, v))
}

// MonthlyQuotaUsdEQ applies the EQ predicate on the "monthly_quota_usd" field.
func MonthlyQuotaUsdEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldMonthlyQuotaUsd, v))
}

// MonthlyQuotaUsdNEQ applies the NEQ predicate on the "monthly_quota_usd" field.
func MonthlyQuotaUsdNEQ(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldMonthlyQuotaUsd, v))
}

// MonthlyQuotaUsdIn applies the In predicate on the "monthly_quota_usd" field.
func MonthlyQuotaUsdIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldMonthlyQuotaUsd, vs...))
}

// MonthlyQuotaUsdNotIn applies the NotIn predicate on the "monthly_quota_usd" field.
func MonthlyQuotaUsdNotIn(vs ...float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldMonthlyQuotaUsd, vs...))
}

// MonthlyQuotaUsdGT applies the GT predicate on the "monthly_quota_usd" field.
func MonthlyQuotaUsdGT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldMonthlyQuotaUsd, v))
}

// MonthlyQuotaUsdGTE applies the GTE predicate on the "monthly_quota_usd" field.
func MonthlyQuotaUsdGTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldMonthlyQuotaUsd, v))
}

// MonthlyQuotaUsdLT applies the LT predicate on the "monthly_quota_usd" field.
func MonthlyQuotaUsdLT(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldMonthlyQuotaUsd, v))
}

// MonthlyQuotaUsdLTE applies the LTE predicate on the "monthly_quota_usd" field.
func MonthlyQuotaUsdLTE(v float64) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldMonthlyQuotaUsd, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GroupsTable, GroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.SubscriptionPlanGroup) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionPlan) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionPlan) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionPlan) predicate.SubscriptionPlan {
	return predicate.SubscriptionPlan(sql.NotPredicates(p))
}
