// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grouppromotion"
)

// GroupPromotionCreate is the builder for creating a GroupPromotion entity.
type GroupPromotionCreate struct {
	config
	mutation *GroupPromotionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *GroupPromotionCreate) SetName(v string) *GroupPromotionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *GroupPromotionCreate) SetDescription(v string) *GroupPromotionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *GroupPromotionCreate) SetNillableDescription(v *string) *GroupPromotionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *GroupPromotionCreate) SetGroupID(v int64) *GroupPromotionCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *GroupPromotionCreate) SetMode(v string) *GroupPromotionCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *GroupPromotionCreate) SetValue(v float64) *GroupPromotionCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *GroupPromotionCreate) SetStartsAt(v time.Time) *GroupPromotionCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetEndsAt sets the "ends_at" field.
func (_c *GroupPromotionCreate) SetEndsAt(v time.Time) *GroupPromotionCreate {
	_c.mutation.SetEndsAt(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *GroupPromotionCreate) SetEnabled(v bool) *GroupPromotionCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *GroupPromotionCreate) SetNillableEnabled(v *bool) *GroupPromotionCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *GroupPromotionCreate) SetCreatedBy(v int64) *GroupPromotionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *GroupPromotionCreate) SetNillableCreatedBy(v *int64) *GroupPromotionCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *GroupPromotionCreate) SetUpdatedBy(v int64) *GroupPromotionCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *GroupPromotionCreate) SetNillableUpdatedBy(v *int64) *GroupPromotionCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupPromotionCreate) SetCreatedAt(v time.Time) *GroupPromotionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupPromotionCreate) SetNillableCreatedAt(v *time.Time) *GroupPromotionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupPromotionCreate) SetUpdatedAt(v time.Time) *GroupPromotionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroupPromotionCreate) SetNillableUpdatedAt(v *time.Time) *GroupPromotionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the GroupPromotionMutation object of the builder.
func (_c *GroupPromotionCreate) Mutation() *GroupPromotionMutation {
	return _c.mutation
}

// Save creates the GroupPromotion in the database.
func (_c *GroupPromotionCreate) Save(ctx context.Context) (*GroupPromotion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupPromotionCreate) SaveX(ctx context.Context) *GroupPromotion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupPromotionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupPromotionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupPromotionCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := grouppromotion.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := grouppromotion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := grouppromotion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupPromotionCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "GroupPromotion.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := grouppromotion.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "GroupPromotion.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupPromotion.group_id"`)}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "GroupPromotion.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := grouppromotion.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "GroupPromotion.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "GroupPromotion.value"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "GroupPromotion.starts_at"`)}
	}
	if _, ok := _c.mutation.EndsAt(); !ok {
		return &ValidationError{Name: "ends_at", err: errors.New(`ent: missing required field "GroupPromotion.ends_at"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "GroupPromotion.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupPromotion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GroupPromotion.updated_at"`)}
	}
	return nil
}

func (_c *GroupPromotionCreate) sqlSave(ctx context.Context) (*GroupPromotion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupPromotionCreate) createSpec() (*GroupPromotion, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupPromotion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(grouppromotion.Table, sqlgraph.NewFieldSpec(grouppromotion.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(grouppromotion.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(grouppromotion.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(grouppromotion.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(grouppromotion.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(grouppromotion.FieldValue, field.TypeFloat64, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(grouppromotion.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.EndsAt(); ok {
		_spec.SetField(grouppromotion.FieldEndsAt, field.TypeTime, value)
		_node.EndsAt = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(grouppromotion.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(grouppromotion.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(grouppromotion.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(grouppromotion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(grouppromotion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupPromotion.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupPromotionUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupPromotionCreate) OnConflict(opts ...sql.ConflictOption) *GroupPromotionUpsertOne {
	_c.conflict = opts
	return &GroupPromotionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupPromotion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupPromotionCreate) OnConflictColumns(columns ...string) *GroupPromotionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupPromotionUpsertOne{
		create: _c,
	}
}

type (
	// GroupPromotionUpsertOne is the builder for "upsert"-ing
	//  one GroupPromotion node.
	GroupPromotionUpsertOne struct {
		create *GroupPromotionCreate
	}

	// GroupPromotionUpsert is the "OnConflict" setter.
	GroupPromotionUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *GroupPromotionUpsert) SetName(v string) *GroupPromotionUpsert {
	u.Set(grouppromotion.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GroupPromotionUpsert) UpdateName() *GroupPromotionUpsert {
	u.SetExcluded(grouppromotion.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *GroupPromotionUpsert) SetDescription(v string) *GroupPromotionUpsert {
	u.Set(grouppromotion.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *GroupPromotionUpsert) UpdateDescription() *GroupPromotionUpsert {
	u.SetExcluded(grouppromotion.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *GroupPromotionUpsert) ClearDescription() *GroupPromotionUpsert {
	u.SetNull(grouppromotion.FieldDescription)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupPromotionUpsert) SetGroupID(v int64) *GroupPromotionUpsert {
	u.Set(grouppromotion.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupPromotionUpsert) UpdateGroupID() *GroupPromotionUpsert {
	u.SetExcluded(grouppromotion.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *GroupPromotionUpsert) AddGroupID(v int64) *GroupPromotionUpsert {
	u.Add(grouppromotion.FieldGroupID, v)
	return u
}

// SetMode sets the "mode" field.
func (u *GroupPromotionUpsert) SetMode(v string) *GroupPromotionUpsert {
	u.Set(grouppromotion.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *GroupPromotionUpsert) UpdateMode() *GroupPromotionUpsert {
	u.SetExcluded(grouppromotion.FieldMode)
	return u
}

// SetValue sets the "value" field.
func (u *GroupPromotionUpsert) SetValue(v float64) *GroupPromotionUpsert {
	u.Set(grouppromotion.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *GroupPromotionUpsert) UpdateValue() *GroupPromotionUpsert {
	u.SetExcluded(grouppromotion.FieldValue)
	return u
}

// AddValue adds v to the "value" field.
func (u *GroupPromotionUpsert) AddValue(v float64) *GroupPromotionUpsert {
	u.Add(grouppromotion.FieldValue, v)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *GroupPromotionUpsert) SetStartsAt(v time.Time) *GroupPromotionUpsert {
	u.Set(grouppromotion.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *GroupPromotionUpsert) UpdateStartsAt() *GroupPromotionUpsert {
	u.SetExcluded(grouppromotion.FieldStartsAt)
	return u
}

// SetEndsAt sets the "ends_at" field.
func (u *GroupPromotionUpsert) SetEndsAt(v time.Time) *GroupPromotionUpsert {
	u.Set(grouppromotion.FieldEndsAt, v)
	return u
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *GroupPromotionUpsert) UpdateEndsAt() *GroupPromotionUpsert {
	u.SetExcluded(grouppromotion.FieldEndsAt)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *GroupPromotionUpsert) SetEnabled(v bool) *GroupPromotionUpsert {
	u.Set(grouppromotion.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *GroupPromotionUpsert) UpdateEnabled() *GroupPromotionUpsert {
	u.SetExcluded(grouppromotion.FieldEnabled)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *GroupPromotionUpsert) SetCreatedBy(v int64) *GroupPromotionUpsert {
	u.Set(grouppromotion.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *GroupPromotionUpsert) UpdateCreatedBy() *GroupPromotionUpsert {
	u.SetExcluded(grouppromotion.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *GroupPromotionUpsert) AddCreatedBy(v int64) *GroupPromotionUpsert {
	u.Add(grouppromotion.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *GroupPromotionUpsert) ClearCreatedBy() *GroupPromotionUpsert {
	u.SetNull(grouppromotion.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *GroupPromotionUpsert) SetUpdatedBy(v int64) *GroupPromotionUpsert {
	u.Set(grouppromotion.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *GroupPromotionUpsert) UpdateUpdatedBy() *GroupPromotionUpsert {
	u.SetExcluded(grouppromotion.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *GroupPromotionUpsert) AddUpdatedBy(v int64) *GroupPromotionUpsert {
	u.Add(grouppromotion.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *GroupPromotionUpsert) ClearUpdatedBy() *GroupPromotionUpsert {
	u.SetNull(grouppromotion.FieldUpdatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupPromotionUpsert) SetUpdatedAt(v time.Time) *GroupPromotionUpsert {
	u.Set(grouppromotion.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupPromotionUpsert) UpdateUpdatedAt() *GroupPromotionUpsert {
	u.SetExcluded(grouppromotion.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GroupPromotion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupPromotionUpsertOne) UpdateNewValues() *GroupPromotionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(grouppromotion.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupPromotion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupPromotionUpsertOne) Ignore() *GroupPromotionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupPromotionUpsertOne) DoNothing() *GroupPromotionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupPromotionCreate.OnConflict
// documentation for more info.
func (u *GroupPromotionUpsertOne) Update(set func(*GroupPromotionUpsert)) *GroupPromotionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupPromotionUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *GroupPromotionUpsertOne) SetName(v string) *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GroupPromotionUpsertOne) UpdateName() *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *GroupPromotionUpsertOne) SetDescription(v string) *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *GroupPromotionUpsertOne) UpdateDescription() *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *GroupPromotionUpsertOne) ClearDescription() *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.ClearDescription()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupPromotionUpsertOne) SetGroupID(v int64) *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *GroupPromotionUpsertOne) AddGroupID(v int64) *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupPromotionUpsertOne) UpdateGroupID() *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateGroupID()
	})
}

// SetMode sets the "mode" field.
func (u *GroupPromotionUpsertOne) SetMode(v string) *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *GroupPromotionUpsertOne) UpdateMode() *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateMode()
	})
}

// SetValue sets the "value" field.
func (u *GroupPromotionUpsertOne) SetValue(v float64) *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetValue(v)
	})
}

// AddValue adds v to the "value" field.
func (u *GroupPromotionUpsertOne) AddValue(v float64) *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.AddValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *GroupPromotionUpsertOne) UpdateValue() *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateValue()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *GroupPromotionUpsertOne) SetStartsAt(v time.Time) *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *GroupPromotionUpsertOne) UpdateStartsAt() *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *GroupPromotionUpsertOne) SetEndsAt(v time.Time) *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *GroupPromotionUpsertOne) UpdateEndsAt() *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateEndsAt()
	})
}

// SetEnabled sets the "enabled" field.
func (u *GroupPromotionUpsertOne) SetEnabled(v bool) *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *GroupPromotionUpsertOne) UpdateEnabled() *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateEnabled()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *GroupPromotionUpsertOne) SetCreatedBy(v int64) *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *GroupPromotionUpsertOne) AddCreatedBy(v int64) *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *GroupPromotionUpsertOne) UpdateCreatedBy() *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *GroupPromotionUpsertOne) ClearCreatedBy() *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *GroupPromotionUpsertOne) SetUpdatedBy(v int64) *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *GroupPromotionUpsertOne) AddUpdatedBy(v int64) *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *GroupPromotionUpsertOne) UpdateUpdatedBy() *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *GroupPromotionUpsertOne) ClearUpdatedBy() *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupPromotionUpsertOne) SetUpdatedAt(v time.Time) *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupPromotionUpsertOne) UpdateUpdatedAt() *GroupPromotionUpsertOne {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GroupPromotionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupPromotionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupPromotionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GroupPromotionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GroupPromotionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GroupPromotionCreateBulk is the builder for creating many GroupPromotion entities in bulk.
type GroupPromotionCreateBulk struct {
	config
	err      error
	builders []*GroupPromotionCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupPromotion entities in the database.
func (_c *GroupPromotionCreateBulk) Save(ctx context.Context) ([]*GroupPromotion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupPromotion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupPromotionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupPromotionCreateBulk) SaveX(ctx context.Context) []*GroupPromotion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupPromotionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupPromotionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupPromotion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupPromotionUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupPromotionCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupPromotionUpsertBulk {
	_c.conflict = opts
	return &GroupPromotionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupPromotion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupPromotionCreateBulk) OnConflictColumns(columns ...string) *GroupPromotionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupPromotionUpsertBulk{
		create: _c,
	}
}

// GroupPromotionUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupPromotion nodes.
type GroupPromotionUpsertBulk struct {
	create *GroupPromotionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupPromotion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupPromotionUpsertBulk) UpdateNewValues() *GroupPromotionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(grouppromotion.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupPromotion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupPromotionUpsertBulk) Ignore() *GroupPromotionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupPromotionUpsertBulk) DoNothing() *GroupPromotionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupPromotionCreateBulk.OnConflict
// documentation for more info.
func (u *GroupPromotionUpsertBulk) Update(set func(*GroupPromotionUpsert)) *GroupPromotionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupPromotionUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *GroupPromotionUpsertBulk) SetName(v string) *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GroupPromotionUpsertBulk) UpdateName() *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *GroupPromotionUpsertBulk) SetDescription(v string) *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *GroupPromotionUpsertBulk) UpdateDescription() *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *GroupPromotionUpsertBulk) ClearDescription() *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.ClearDescription()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupPromotionUpsertBulk) SetGroupID(v int64) *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *GroupPromotionUpsertBulk) AddGroupID(v int64) *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupPromotionUpsertBulk) UpdateGroupID() *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateGroupID()
	})
}

// SetMode sets the "mode" field.
func (u *GroupPromotionUpsertBulk) SetMode(v string) *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *GroupPromotionUpsertBulk) UpdateMode() *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateMode()
	})
}

// SetValue sets the "value" field.
func (u *GroupPromotionUpsertBulk) SetValue(v float64) *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetValue(v)
	})
}

// AddValue adds v to the "value" field.
func (u *GroupPromotionUpsertBulk) AddValue(v float64) *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.AddValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *GroupPromotionUpsertBulk) UpdateValue() *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateValue()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *GroupPromotionUpsertBulk) SetStartsAt(v time.Time) *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *GroupPromotionUpsertBulk) UpdateStartsAt() *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *GroupPromotionUpsertBulk) SetEndsAt(v time.Time) *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *GroupPromotionUpsertBulk) UpdateEndsAt() *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateEndsAt()
	})
}

// SetEnabled sets the "enabled" field.
func (u *GroupPromotionUpsertBulk) SetEnabled(v bool) *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *GroupPromotionUpsertBulk) UpdateEnabled() *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateEnabled()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *GroupPromotionUpsertBulk) SetCreatedBy(v int64) *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *GroupPromotionUpsertBulk) AddCreatedBy(v int64) *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *GroupPromotionUpsertBulk) UpdateCreatedBy() *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *GroupPromotionUpsertBulk) ClearCreatedBy() *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *GroupPromotionUpsertBulk) SetUpdatedBy(v int64) *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *GroupPromotionUpsertBulk) AddUpdatedBy(v int64) *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *GroupPromotionUpsertBulk) UpdateUpdatedBy() *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *GroupPromotionUpsertBulk) ClearUpdatedBy() *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupPromotionUpsertBulk) SetUpdatedAt(v time.Time) *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupPromotionUpsertBulk) UpdateUpdatedAt() *GroupPromotionUpsertBulk {
	return u.Update(func(s *GroupPromotionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GroupPromotionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupPromotionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupPromotionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupPromotionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
