// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grouppromotion"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupPromotionUpdate is the builder for updating GroupPromotion entities.
type GroupPromotionUpdate struct {
	config
	hooks    []Hook
	mutation *GroupPromotionMutation
}

// Where appends a list predicates to the GroupPromotionUpdate builder.
func (_u *GroupPromotionUpdate) Where(ps ...predicate.GroupPromotion) *GroupPromotionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *GroupPromotionUpdate) SetName(v string) *GroupPromotionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GroupPromotionUpdate) SetNillableName(v *string) *GroupPromotionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *GroupPromotionUpdate) SetDescription(v string) *GroupPromotionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GroupPromotionUpdate) SetNillableDescription(v *string) *GroupPromotionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *GroupPromotionUpdate) ClearDescription() *GroupPromotionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupPromotionUpdate) SetGroupID(v int64) *GroupPromotionUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupPromotionUpdate) SetNillableGroupID(v *int64) *GroupPromotionUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *GroupPromotionUpdate) AddGroupID(v int64) *GroupPromotionUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetMode sets the "mode" field.
func (_u *GroupPromotionUpdate) SetMode(v string) *GroupPromotionUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *GroupPromotionUpdate) SetNillableMode(v *string) *GroupPromotionUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *GroupPromotionUpdate) SetValue(v float64) *GroupPromotionUpdate {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *GroupPromotionUpdate) SetNillableValue(v *float64) *GroupPromotionUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *GroupPromotionUpdate) AddValue(v float64) *GroupPromotionUpdate {
	_u.mutation.AddValue(v)
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *GroupPromotionUpdate) SetStartsAt(v time.Time) *GroupPromotionUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *GroupPromotionUpdate) SetNillableStartsAt(v *time.Time) *GroupPromotionUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *GroupPromotionUpdate) SetEndsAt(v time.Time) *GroupPromotionUpdate {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *GroupPromotionUpdate) SetNillableEndsAt(v *time.Time) *GroupPromotionUpdate {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *GroupPromotionUpdate) SetEnabled(v bool) *GroupPromotionUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *GroupPromotionUpdate) SetNillableEnabled(v *bool) *GroupPromotionUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *GroupPromotionUpdate) SetCreatedBy(v int64) *GroupPromotionUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *GroupPromotionUpdate) SetNillableCreatedBy(v *int64) *GroupPromotionUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *GroupPromotionUpdate) AddCreatedBy(v int64) *GroupPromotionUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *GroupPromotionUpdate) ClearCreatedBy() *GroupPromotionUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *GroupPromotionUpdate) SetUpdatedBy(v int64) *GroupPromotionUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *GroupPromotionUpdate) SetNillableUpdatedBy(v *int64) *GroupPromotionUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *GroupPromotionUpdate) AddUpdatedBy(v int64) *GroupPromotionUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *GroupPromotionUpdate) ClearUpdatedBy() *GroupPromotionUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupPromotionUpdate) SetUpdatedAt(v time.Time) *GroupPromotionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GroupPromotionMutation object of the builder.
func (_u *GroupPromotionUpdate) Mutation() *GroupPromotionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupPromotionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupPromotionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupPromotionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupPromotionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupPromotionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := grouppromotion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupPromotionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := grouppromotion.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "GroupPromotion.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := grouppromotion.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "GroupPromotion.mode": %w`, err)}
		}
	}
	return nil
}

func (_u *GroupPromotionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grouppromotion.Table, grouppromotion.Columns, sqlgraph.NewFieldSpec(grouppromotion.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(grouppromotion.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(grouppromotion.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(grouppromotion.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(grouppromotion.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(grouppromotion.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(grouppromotion.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(grouppromotion.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(grouppromotion.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(grouppromotion.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(grouppromotion.FieldEndsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(grouppromotion.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(grouppromotion.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(grouppromotion.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(grouppromotion.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(grouppromotion.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(grouppromotion.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(grouppromotion.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(grouppromotion.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grouppromotion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupPromotionUpdateOne is the builder for updating a single GroupPromotion entity.
type GroupPromotionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupPromotionMutation
}

// SetName sets the "name" field.
func (_u *GroupPromotionUpdateOne) SetName(v string) *GroupPromotionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GroupPromotionUpdateOne) SetNillableName(v *string) *GroupPromotionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *GroupPromotionUpdateOne) SetDescription(v string) *GroupPromotionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GroupPromotionUpdateOne) SetNillableDescription(v *string) *GroupPromotionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *GroupPromotionUpdateOne) ClearDescription() *GroupPromotionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupPromotionUpdateOne) SetGroupID(v int64) *GroupPromotionUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupPromotionUpdateOne) SetNillableGroupID(v *int64) *GroupPromotionUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *GroupPromotionUpdateOne) AddGroupID(v int64) *GroupPromotionUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetMode sets the "mode" field.
func (_u *GroupPromotionUpdateOne) SetMode(v string) *GroupPromotionUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *GroupPromotionUpdateOne) SetNillableMode(v *string) *GroupPromotionUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *GroupPromotionUpdateOne) SetValue(v float64) *GroupPromotionUpdateOne {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *GroupPromotionUpdateOne) SetNillableValue(v *float64) *GroupPromotionUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *GroupPromotionUpdateOne) AddValue(v float64) *GroupPromotionUpdateOne {
	_u.mutation.AddValue(v)
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *GroupPromotionUpdateOne) SetStartsAt(v time.Time) *GroupPromotionUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *GroupPromotionUpdateOne) SetNillableStartsAt(v *time.Time) *GroupPromotionUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *GroupPromotionUpdateOne) SetEndsAt(v time.Time) *GroupPromotionUpdateOne {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *GroupPromotionUpdateOne) SetNillableEndsAt(v *time.Time) *GroupPromotionUpdateOne {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *GroupPromotionUpdateOne) SetEnabled(v bool) *GroupPromotionUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *GroupPromotionUpdateOne) SetNillableEnabled(v *bool) *GroupPromotionUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *GroupPromotionUpdateOne) SetCreatedBy(v int64) *GroupPromotionUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *GroupPromotionUpdateOne) SetNillableCreatedBy(v *int64) *GroupPromotionUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *GroupPromotionUpdateOne) AddCreatedBy(v int64) *GroupPromotionUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *GroupPromotionUpdateOne) ClearCreatedBy() *GroupPromotionUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *GroupPromotionUpdateOne) SetUpdatedBy(v int64) *GroupPromotionUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *GroupPromotionUpdateOne) SetNillableUpdatedBy(v *int64) *GroupPromotionUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *GroupPromotionUpdateOne) AddUpdatedBy(v int64) *GroupPromotionUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *GroupPromotionUpdateOne) ClearUpdatedBy() *GroupPromotionUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupPromotionUpdateOne) SetUpdatedAt(v time.Time) *GroupPromotionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GroupPromotionMutation object of the builder.
func (_u *GroupPromotionUpdateOne) Mutation() *GroupPromotionMutation {
	return _u.mutation
}

// Where appends a list predicates to the GroupPromotionUpdate builder.
func (_u *GroupPromotionUpdateOne) Where(ps ...predicate.GroupPromotion) *GroupPromotionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupPromotionUpdateOne) Select(field string, fields ...string) *GroupPromotionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupPromotion entity.
func (_u *GroupPromotionUpdateOne) Save(ctx context.Context) (*GroupPromotion, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupPromotionUpdateOne) SaveX(ctx context.Context) *GroupPromotion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupPromotionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupPromotionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupPromotionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := grouppromotion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupPromotionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := grouppromotion.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "GroupPromotion.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := grouppromotion.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "GroupPromotion.mode": %w`, err)}
		}
	}
	return nil
}

func (_u *GroupPromotionUpdateOne) sqlSave(ctx context.Context) (_node *GroupPromotion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grouppromotion.Table, grouppromotion.Columns, sqlgraph.NewFieldSpec(grouppromotion.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupPromotion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, grouppromotion.FieldID)
		for _, f := range fields {
			if !grouppromotion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != grouppromotion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(grouppromotion.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(grouppromotion.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(grouppromotion.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(grouppromotion.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(grouppromotion.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(grouppromotion.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(grouppromotion.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(grouppromotion.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(grouppromotion.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(grouppromotion.FieldEndsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(grouppromotion.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(grouppromotion.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(grouppromotion.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(grouppromotion.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(grouppromotion.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(grouppromotion.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(grouppromotion.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(grouppromotion.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &GroupPromotion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grouppromotion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
