// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grouppromotion"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupPromotionDelete is the builder for deleting a GroupPromotion entity.
type GroupPromotionDelete struct {
	config
	hooks    []Hook
	mutation *GroupPromotionMutation
}

// Where appends a list predicates to the GroupPromotionDelete builder.
func (_d *GroupPromotionDelete) Where(ps ...predicate.GroupPromotion) *GroupPromotionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GroupPromotionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupPromotionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GroupPromotionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(grouppromotion.Table, sqlgraph.NewFieldSpec(grouppromotion.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GroupPromotionDeleteOne is the builder for deleting a single GroupPromotion entity.
type GroupPromotionDeleteOne struct {
	_d *GroupPromotionDelete
}

// Where appends a list predicates to the GroupPromotionDelete builder.
func (_d *GroupPromotionDeleteOne) Where(ps ...predicate.GroupPromotion) *GroupPromotionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GroupPromotionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{grouppromotion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupPromotionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
