// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionpurchase"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionpurchasegroup"
)

// SubscriptionPurchaseGroup is the model entity for the SubscriptionPurchaseGroup schema.
type SubscriptionPurchaseGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// PurchaseID holds the value of the "purchase_id" field.
	PurchaseID int64 `json:"purchase_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// GroupName holds the value of the "group_name" field.
	GroupName string `json:"group_name,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionPurchaseGroupQuery when eager-loading is set.
	Edges        SubscriptionPurchaseGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionPurchaseGroupEdges holds the relations/edges for other nodes in the graph.
type SubscriptionPurchaseGroupEdges struct {
	// Purchase holds the value of the purchase edge.
	Purchase *SubscriptionPurchase `json:"purchase,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PurchaseOrErr returns the Purchase value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionPurchaseGroupEdges) PurchaseOrErr() (*SubscriptionPurchase, error) {
	if e.Purchase != nil {
		return e.Purchase, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: subscriptionpurchase.Label}
	}
	return nil, &NotLoadedError{edge: "purchase"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionPurchaseGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionpurchasegroup.FieldID, subscriptionpurchasegroup.FieldPurchaseID, subscriptionpurchasegroup.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case subscriptionpurchasegroup.FieldGroupName, subscriptionpurchasegroup.FieldPlatform:
			values[i] = new(sql.NullString)
		case subscriptionpurchasegroup.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionPurchaseGroup fields.
func (_m *SubscriptionPurchaseGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionpurchasegroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionpurchasegroup.FieldPurchaseID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_id", values[i])
			} else if value.Valid {
				_m.PurchaseID = value.Int64
			}
		case subscriptionpurchasegroup.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case subscriptionpurchasegroup.FieldGroupName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_name", values[i])
			} else if value.Valid {
				_m.GroupName = value.String
			}
		case subscriptionpurchasegroup.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case subscriptionpurchasegroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionPurchaseGroup.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionPurchaseGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPurchase queries the "purchase" edge of the SubscriptionPurchaseGroup entity.
func (_m *SubscriptionPurchaseGroup) QueryPurchase() *SubscriptionPurchaseQuery {
	return NewSubscriptionPurchaseGroupClient(_m.config).QueryPurchase(_m)
}

// Update returns a builder for updating this SubscriptionPurchaseGroup.
// Note that you need to call SubscriptionPurchaseGroup.Unwrap() before calling this method if this SubscriptionPurchaseGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionPurchaseGroup) Update() *SubscriptionPurchaseGroupUpdateOne {
	return NewSubscriptionPurchaseGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionPurchaseGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionPurchaseGroup) Unwrap() *SubscriptionPurchaseGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionPurchaseGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionPurchaseGroup) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionPurchaseGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("purchase_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PurchaseID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("group_name=")
	builder.WriteString(_m.GroupName)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionPurchaseGroups is a parsable slice of SubscriptionPurchaseGroup.
type SubscriptionPurchaseGroups []*SubscriptionPurchaseGroup
