// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionpurchase"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionpurchasegroup"
)

// SubscriptionPurchaseGroupUpdate is the builder for updating SubscriptionPurchaseGroup entities.
type SubscriptionPurchaseGroupUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionPurchaseGroupMutation
}

// Where appends a list predicates to the SubscriptionPurchaseGroupUpdate builder.
func (_u *SubscriptionPurchaseGroupUpdate) Where(ps ...predicate.SubscriptionPurchaseGroup) *SubscriptionPurchaseGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPurchaseID sets the "purchase_id" field.
func (_u *SubscriptionPurchaseGroupUpdate) SetPurchaseID(v int64) *SubscriptionPurchaseGroupUpdate {
	_u.mutation.SetPurchaseID(v)
	return _u
}

// SetNillablePurchaseID sets the "purchase_id" field if the given value is not nil.
func (_u *SubscriptionPurchaseGroupUpdate) SetNillablePurchaseID(v *int64) *SubscriptionPurchaseGroupUpdate {
	if v != nil {
		_u.SetPurchaseID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionPurchaseGroupUpdate) SetGroupID(v int64) *SubscriptionPurchaseGroupUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionPurchaseGroupUpdate) SetNillableGroupID(v *int64) *SubscriptionPurchaseGroupUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SubscriptionPurchaseGroupUpdate) AddGroupID(v int64) *SubscriptionPurchaseGroupUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *SubscriptionPurchaseGroupUpdate) SetGroupName(v string) *SubscriptionPurchaseGroupUpdate {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *SubscriptionPurchaseGroupUpdate) SetNillableGroupName(v *string) *SubscriptionPurchaseGroupUpdate {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *SubscriptionPurchaseGroupUpdate) SetPlatform(v string) *SubscriptionPurchaseGroupUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *SubscriptionPurchaseGroupUpdate) SetNillablePlatform(v *string) *SubscriptionPurchaseGroupUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetPurchase sets the "purchase" edge to the SubscriptionPurchase entity.
func (_u *SubscriptionPurchaseGroupUpdate) SetPurchase(v *SubscriptionPurchase) *SubscriptionPurchaseGroupUpdate {
	return _u.SetPurchaseID(v.ID)
}

// Mutation returns the SubscriptionPurchaseGroupMutation object of the builder.
func (_u *SubscriptionPurchaseGroupUpdate) Mutation() *SubscriptionPurchaseGroupMutation {
	return _u.mutation
}

// ClearPurchase clears the "purchase" edge to the SubscriptionPurchase entity.
func (_u *SubscriptionPurchaseGroupUpdate) ClearPurchase() *SubscriptionPurchaseGroupUpdate {
	_u.mutation.ClearPurchase()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionPurchaseGroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPurchaseGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionPurchaseGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPurchaseGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionPurchaseGroupUpdate) check() error {
	if v, ok := _u.mutation.GroupName(); ok {
		if err := subscriptionpurchasegroup.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPurchaseGroup.group_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := subscriptionpurchasegroup.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPurchaseGroup.platform": %w`, err)}
		}
	}
	if _u.mutation.PurchaseCleared() && len(_u.mutation.PurchaseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionPurchaseGroup.purchase"`)
	}
	return nil
}

func (_u *SubscriptionPurchaseGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionpurchasegroup.Table, subscriptionpurchasegroup.Columns, sqlgraph.NewFieldSpec(subscriptionpurchasegroup.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(subscriptionpurchasegroup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(subscriptionpurchasegroup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(subscriptionpurchasegroup.FieldGroupName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(subscriptionpurchasegroup.FieldPlatform, field.TypeString, value)
	}
	if _u.mutation.PurchaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionpurchasegroup.PurchaseTable,
			Columns: []string{subscriptionpurchasegroup.PurchaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionpurchase.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PurchaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionpurchasegroup.PurchaseTable,
			Columns: []string{subscriptionpurchasegroup.PurchaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionpurchase.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionpurchasegroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionPurchaseGroupUpdateOne is the builder for updating a single SubscriptionPurchaseGroup entity.
type SubscriptionPurchaseGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionPurchaseGroupMutation
}

// SetPurchaseID sets the "purchase_id" field.
func (_u *SubscriptionPurchaseGroupUpdateOne) SetPurchaseID(v int64) *SubscriptionPurchaseGroupUpdateOne {
	_u.mutation.SetPurchaseID(v)
	return _u
}

// SetNillablePurchaseID sets the "purchase_id" field if the given value is not nil.
func (_u *SubscriptionPurchaseGroupUpdateOne) SetNillablePurchaseID(v *int64) *SubscriptionPurchaseGroupUpdateOne {
	if v != nil {
		_u.SetPurchaseID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionPurchaseGroupUpdateOne) SetGroupID(v int64) *SubscriptionPurchaseGroupUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionPurchaseGroupUpdateOne) SetNillableGroupID(v *int64) *SubscriptionPurchaseGroupUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SubscriptionPurchaseGroupUpdateOne) AddGroupID(v int64) *SubscriptionPurchaseGroupUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *SubscriptionPurchaseGroupUpdateOne) SetGroupName(v string) *SubscriptionPurchaseGroupUpdateOne {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *SubscriptionPurchaseGroupUpdateOne) SetNillableGroupName(v *string) *SubscriptionPurchaseGroupUpdateOne {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *SubscriptionPurchaseGroupUpdateOne) SetPlatform(v string) *SubscriptionPurchaseGroupUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *SubscriptionPurchaseGroupUpdateOne) SetNillablePlatform(v *string) *SubscriptionPurchaseGroupUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetPurchase sets the "purchase" edge to the SubscriptionPurchase entity.
func (_u *SubscriptionPurchaseGroupUpdateOne) SetPurchase(v *SubscriptionPurchase) *SubscriptionPurchaseGroupUpdateOne {
	return _u.SetPurchaseID(v.ID)
}

// Mutation returns the SubscriptionPurchaseGroupMutation object of the builder.
func (_u *SubscriptionPurchaseGroupUpdateOne) Mutation() *SubscriptionPurchaseGroupMutation {
	return _u.mutation
}

// ClearPurchase clears the "purchase" edge to the SubscriptionPurchase entity.
func (_u *SubscriptionPurchaseGroupUpdateOne) ClearPurchase() *SubscriptionPurchaseGroupUpdateOne {
	_u.mutation.ClearPurchase()
	return _u
}

// Where appends a list predicates to the SubscriptionPurchaseGroupUpdate builder.
func (_u *SubscriptionPurchaseGroupUpdateOne) Where(ps ...predicate.SubscriptionPurchaseGroup) *SubscriptionPurchaseGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionPurchaseGroupUpdateOne) Select(field string, fields ...string) *SubscriptionPurchaseGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionPurchaseGroup entity.
func (_u *SubscriptionPurchaseGroupUpdateOne) Save(ctx context.Context) (*SubscriptionPurchaseGroup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPurchaseGroupUpdateOne) SaveX(ctx context.Context) *SubscriptionPurchaseGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionPurchaseGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPurchaseGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionPurchaseGroupUpdateOne) check() error {
	if v, ok := _u.mutation.GroupName(); ok {
		if err := subscriptionpurchasegroup.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPurchaseGroup.group_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := subscriptionpurchasegroup.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPurchaseGroup.platform": %w`, err)}
		}
	}
	if _u.mutation.PurchaseCleared() && len(_u.mutation.PurchaseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionPurchaseGroup.purchase"`)
	}
	return nil
}

func (_u *SubscriptionPurchaseGroupUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionPurchaseGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionpurchasegroup.Table, subscriptionpurchasegroup.Columns, sqlgraph.NewFieldSpec(subscriptionpurchasegroup.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionPurchaseGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionpurchasegroup.FieldID)
		for _, f := range fields {
			if !subscriptionpurchasegroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionpurchasegroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(subscriptionpurchasegroup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(subscriptionpurchasegroup.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(subscriptionpurchasegroup.FieldGroupName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(subscriptionpurchasegroup.FieldPlatform, field.TypeString, value)
	}
	if _u.mutation.PurchaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionpurchasegroup.PurchaseTable,
			Columns: []string{subscriptionpurchasegroup.PurchaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionpurchase.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PurchaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionpurchasegroup.PurchaseTable,
			Columns: []string{subscriptionpurchasegroup.PurchaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionpurchase.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionPurchaseGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionpurchasegroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
