// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionpurchase"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionpurchasegroup"
)

// SubscriptionPurchaseGroupCreate is the builder for creating a SubscriptionPurchaseGroup entity.
type SubscriptionPurchaseGroupCreate struct {
	config
	mutation *SubscriptionPurchaseGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPurchaseID sets the "purchase_id" field.
func (_c *SubscriptionPurchaseGroupCreate) SetPurchaseID(v int64) *SubscriptionPurchaseGroupCreate {
	_c.mutation.SetPurchaseID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *SubscriptionPurchaseGroupCreate) SetGroupID(v int64) *SubscriptionPurchaseGroupCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetGroupName sets the "group_name" field.
func (_c *SubscriptionPurchaseGroupCreate) SetGroupName(v string) *SubscriptionPurchaseGroupCreate {
	_c.mutation.SetGroupName(v)
	return _c
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_c *SubscriptionPurchaseGroupCreate) SetNillableGroupName(v *string) *SubscriptionPurchaseGroupCreate {
	if v != nil {
		_c.SetGroupName(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *SubscriptionPurchaseGroupCreate) SetPlatform(v string) *SubscriptionPurchaseGroupCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *SubscriptionPurchaseGroupCreate) SetNillablePlatform(v *string) *SubscriptionPurchaseGroupCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionPurchaseGroupCreate) SetCreatedAt(v time.Time) *SubscriptionPurchaseGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionPurchaseGroupCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionPurchaseGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetPurchase sets the "purchase" edge to the SubscriptionPurchase entity.
func (_c *SubscriptionPurchaseGroupCreate) SetPurchase(v *SubscriptionPurchase) *SubscriptionPurchaseGroupCreate {
	return _c.SetPurchaseID(v.ID)
}

// Mutation returns the SubscriptionPurchaseGroupMutation object of the builder.
func (_c *SubscriptionPurchaseGroupCreate) Mutation() *SubscriptionPurchaseGroupMutation {
	return _c.mutation
}

// Save creates the SubscriptionPurchaseGroup in the database.
func (_c *SubscriptionPurchaseGroupCreate) Save(ctx context.Context) (*SubscriptionPurchaseGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionPurchaseGroupCreate) SaveX(ctx context.Context) *SubscriptionPurchaseGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPurchaseGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPurchaseGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionPurchaseGroupCreate) defaults() {
	if _, ok := _c.mutation.GroupName(); !ok {
		v := subscriptionpurchasegroup.DefaultGroupName
		_c.mutation.SetGroupName(v)
	}
	if _, ok := _c.mutation.Platform(); !ok {
		v := subscriptionpurchasegroup.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionpurchasegroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionPurchaseGroupCreate) check() error {
	if _, ok := _c.mutation.PurchaseID(); !ok {
		return &ValidationError{Name: "purchase_id", err: errors.New(`ent: missing required field "SubscriptionPurchaseGroup.purchase_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "SubscriptionPurchaseGroup.group_id"`)}
	}
	if _, ok := _c.mutation.GroupName(); !ok {
		return &ValidationError{Name: "group_name", err: errors.New(`ent: missing required field "SubscriptionPurchaseGroup.group_name"`)}
	}
	if v, ok := _c.mutation.GroupName(); ok {
		if err := subscriptionpurchasegroup.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPurchaseGroup.group_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "SubscriptionPurchaseGroup.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := subscriptionpurchasegroup.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPurchaseGroup.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionPurchaseGroup.created_at"`)}
	}
	if len(_c.mutation.PurchaseIDs()) == 0 {
		return &ValidationError{Name: "purchase", err: errors.New(`ent: missing required edge "SubscriptionPurchaseGroup.purchase"`)}
	}
	return nil
}

func (_c *SubscriptionPurchaseGroupCreate) sqlSave(ctx context.Context) (*SubscriptionPurchaseGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionPurchaseGroupCreate) createSpec() (*SubscriptionPurchaseGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionPurchaseGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionpurchasegroup.Table, sqlgraph.NewFieldSpec(subscriptionpurchasegroup.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(subscriptionpurchasegroup.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.GroupName(); ok {
		_spec.SetField(subscriptionpurchasegroup.FieldGroupName, field.TypeString, value)
		_node.GroupName = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(subscriptionpurchasegroup.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionpurchasegroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PurchaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionpurchasegroup.PurchaseTable,
			Columns: []string{subscriptionpurchasegroup.PurchaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionpurchase.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PurchaseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionPurchaseGroup.Create().
//		SetPurchaseID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionPurchaseGroupUpsert) {
//			SetPurchaseID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionPurchaseGroupCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionPurchaseGroupUpsertOne {
	_c.conflict = opts
	return &SubscriptionPurchaseGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionPurchaseGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionPurchaseGroupCreate) OnConflictColumns(columns ...string) *SubscriptionPurchaseGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionPurchaseGroupUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionPurchaseGroupUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionPurchaseGroup node.
	SubscriptionPurchaseGroupUpsertOne struct {
		create *SubscriptionPurchaseGroupCreate
	}

	// SubscriptionPurchaseGroupUpsert is the "OnConflict" setter.
	SubscriptionPurchaseGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetPurchaseID sets the "purchase_id" field.
func (u *SubscriptionPurchaseGroupUpsert) SetPurchaseID(v int64) *SubscriptionPurchaseGroupUpsert {
	u.Set(subscriptionpurchasegroup.FieldPurchaseID, v)
	return u
}

// UpdatePurchaseID sets the "purchase_id" field to the value that was provided on create.
func (u *SubscriptionPurchaseGroupUpsert) UpdatePurchaseID() *SubscriptionPurchaseGroupUpsert {
	u.SetExcluded(subscriptionpurchasegroup.FieldPurchaseID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionPurchaseGroupUpsert) SetGroupID(v int64) *SubscriptionPurchaseGroupUpsert {
	u.Set(subscriptionpurchasegroup.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionPurchaseGroupUpsert) UpdateGroupID() *SubscriptionPurchaseGroupUpsert {
	u.SetExcluded(subscriptionpurchasegroup.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *SubscriptionPurchaseGroupUpsert) AddGroupID(v int64) *SubscriptionPurchaseGroupUpsert {
	u.Add(subscriptionpurchasegroup.FieldGroupID, v)
	return u
}

// SetGroupName sets the "group_name" field.
func (u *SubscriptionPurchaseGroupUpsert) SetGroupName(v string) *SubscriptionPurchaseGroupUpsert {
	u.Set(subscriptionpurchasegroup.FieldGroupName, v)
	return u
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *SubscriptionPurchaseGroupUpsert) UpdateGroupName() *SubscriptionPurchaseGroupUpsert {
	u.SetExcluded(subscriptionpurchasegroup.FieldGroupName)
	return u
}

// SetPlatform sets the "platform" field.
func (u *SubscriptionPurchaseGroupUpsert) SetPlatform(v string) *SubscriptionPurchaseGroupUpsert {
	u.Set(subscriptionpurchasegroup.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *SubscriptionPurchaseGroupUpsert) UpdatePlatform() *SubscriptionPurchaseGroupUpsert {
	u.SetExcluded(subscriptionpurchasegroup.FieldPlatform)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionPurchaseGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionPurchaseGroupUpsertOne) UpdateNewValues() *SubscriptionPurchaseGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionpurchasegroup.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionPurchaseGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionPurchaseGroupUpsertOne) Ignore() *SubscriptionPurchaseGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionPurchaseGroupUpsertOne) DoNothing() *SubscriptionPurchaseGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionPurchaseGroupCreate.OnConflict
// documentation for more info.
func (u *SubscriptionPurchaseGroupUpsertOne) Update(set func(*SubscriptionPurchaseGroupUpsert)) *SubscriptionPurchaseGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionPurchaseGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetPurchaseID sets the "purchase_id" field.
func (u *SubscriptionPurchaseGroupUpsertOne) SetPurchaseID(v int64) *SubscriptionPurchaseGroupUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.SetPurchaseID(v)
	})
}

// UpdatePurchaseID sets the "purchase_id" field to the value that was provided on create.
func (u *SubscriptionPurchaseGroupUpsertOne) UpdatePurchaseID() *SubscriptionPurchaseGroupUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.UpdatePurchaseID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionPurchaseGroupUpsertOne) SetGroupID(v int64) *SubscriptionPurchaseGroupUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *SubscriptionPurchaseGroupUpsertOne) AddGroupID(v int64) *SubscriptionPurchaseGroupUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionPurchaseGroupUpsertOne) UpdateGroupID() *SubscriptionPurchaseGroupUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.UpdateGroupID()
	})
}

// SetGroupName sets the "group_name" field.
func (u *SubscriptionPurchaseGroupUpsertOne) SetGroupName(v string) *SubscriptionPurchaseGroupUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *SubscriptionPurchaseGroupUpsertOne) UpdateGroupName() *SubscriptionPurchaseGroupUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.UpdateGroupName()
	})
}

// SetPlatform sets the "platform" field.
func (u *SubscriptionPurchaseGroupUpsertOne) SetPlatform(v string) *SubscriptionPurchaseGroupUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *SubscriptionPurchaseGroupUpsertOne) UpdatePlatform() *SubscriptionPurchaseGroupUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.UpdatePlatform()
	})
}

// Exec executes the query.
func (u *SubscriptionPurchaseGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionPurchaseGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionPurchaseGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionPurchaseGroupUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionPurchaseGroupUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionPurchaseGroupCreateBulk is the builder for creating many SubscriptionPurchaseGroup entities in bulk.
type SubscriptionPurchaseGroupCreateBulk struct {
	config
	err      error
	builders []*SubscriptionPurchaseGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionPurchaseGroup entities in the database.
func (_c *SubscriptionPurchaseGroupCreateBulk) Save(ctx context.Context) ([]*SubscriptionPurchaseGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionPurchaseGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionPurchaseGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionPurchaseGroupCreateBulk) SaveX(ctx context.Context) []*SubscriptionPurchaseGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPurchaseGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPurchaseGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionPurchaseGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionPurchaseGroupUpsert) {
//			SetPurchaseID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionPurchaseGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionPurchaseGroupUpsertBulk {
	_c.conflict = opts
	return &SubscriptionPurchaseGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionPurchaseGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionPurchaseGroupCreateBulk) OnConflictColumns(columns ...string) *SubscriptionPurchaseGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionPurchaseGroupUpsertBulk{
		create: _c,
	}
}

// SubscriptionPurchaseGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionPurchaseGroup nodes.
type SubscriptionPurchaseGroupUpsertBulk struct {
	create *SubscriptionPurchaseGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionPurchaseGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionPurchaseGroupUpsertBulk) UpdateNewValues() *SubscriptionPurchaseGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionpurchasegroup.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionPurchaseGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionPurchaseGroupUpsertBulk) Ignore() *SubscriptionPurchaseGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionPurchaseGroupUpsertBulk) DoNothing() *SubscriptionPurchaseGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionPurchaseGroupCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionPurchaseGroupUpsertBulk) Update(set func(*SubscriptionPurchaseGroupUpsert)) *SubscriptionPurchaseGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionPurchaseGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetPurchaseID sets the "purchase_id" field.
func (u *SubscriptionPurchaseGroupUpsertBulk) SetPurchaseID(v int64) *SubscriptionPurchaseGroupUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.SetPurchaseID(v)
	})
}

// UpdatePurchaseID sets the "purchase_id" field to the value that was provided on create.
func (u *SubscriptionPurchaseGroupUpsertBulk) UpdatePurchaseID() *SubscriptionPurchaseGroupUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.UpdatePurchaseID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionPurchaseGroupUpsertBulk) SetGroupID(v int64) *SubscriptionPurchaseGroupUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *SubscriptionPurchaseGroupUpsertBulk) AddGroupID(v int64) *SubscriptionPurchaseGroupUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionPurchaseGroupUpsertBulk) UpdateGroupID() *SubscriptionPurchaseGroupUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.UpdateGroupID()
	})
}

// SetGroupName sets the "group_name" field.
func (u *SubscriptionPurchaseGroupUpsertBulk) SetGroupName(v string) *SubscriptionPurchaseGroupUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *SubscriptionPurchaseGroupUpsertBulk) UpdateGroupName() *SubscriptionPurchaseGroupUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.UpdateGroupName()
	})
}

// SetPlatform sets the "platform" field.
func (u *SubscriptionPurchaseGroupUpsertBulk) SetPlatform(v string) *SubscriptionPurchaseGroupUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *SubscriptionPurchaseGroupUpsertBulk) UpdatePlatform() *SubscriptionPurchaseGroupUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseGroupUpsert) {
		s.UpdatePlatform()
	})
}

// Exec executes the query.
func (u *SubscriptionPurchaseGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionPurchaseGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionPurchaseGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionPurchaseGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
