// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionpurchasegroup"
)

// SubscriptionPurchaseGroupDelete is the builder for deleting a SubscriptionPurchaseGroup entity.
type SubscriptionPurchaseGroupDelete struct {
	config
	hooks    []Hook
	mutation *SubscriptionPurchaseGroupMutation
}

// Where appends a list predicates to the SubscriptionPurchaseGroupDelete builder.
func (_d *SubscriptionPurchaseGroupDelete) Where(ps ...predicate.SubscriptionPurchaseGroup) *SubscriptionPurchaseGroupDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SubscriptionPurchaseGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SubscriptionPurchaseGroupDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SubscriptionPurchaseGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(subscriptionpurchasegroup.Table, sqlgraph.NewFieldSpec(subscriptionpurchasegroup.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SubscriptionPurchaseGroupDeleteOne is the builder for deleting a single SubscriptionPurchaseGroup entity.
type SubscriptionPurchaseGroupDeleteOne struct {
	_d *SubscriptionPurchaseGroupDelete
}

// Where appends a list predicates to the SubscriptionPurchaseGroupDelete builder.
func (_d *SubscriptionPurchaseGroupDeleteOne) Where(ps ...predicate.SubscriptionPurchaseGroup) *SubscriptionPurchaseGroupDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SubscriptionPurchaseGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{subscriptionpurchasegroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SubscriptionPurchaseGroupDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
