package service

import (
	"context"
	"time"
)

// MonitorBodyOverrideMode ???????????
//
//   - off     ?? adapter ?? body??? BodyOverride?
//   - merge   adapter ?? body ? BodyOverride ?????????
//     model/messages/contents ?????? checker ???????????
//   - replace ??? BodyOverride ?? body??? challenge ???
//     ?? HTTP 2xx + ???????????????? body?
const (
	MonitorBodyOverrideModeOff     = "off"
	MonitorBodyOverrideModeMerge   = "merge"
	MonitorBodyOverrideModeReplace = "replace"
	MonitorSourceDirectUpstream    = "direct_upstream"
	MonitorSourceInternalGateway   = "internal_gateway"
)

// MonitorAPIMode ?? OpenAI provider ??????
//
//   - chat_completions  OpenAI-compatible Chat Completions: /v1/chat/completions + messages
//   - responses         OpenAI Responses API: /v1/responses + instructions/input
//   - models            OpenAI Models API: /v1/models, verifies authentication and model availability
//   - images            OpenAI Images API: /v1/images/generations, generates one real test image
//
// ? OpenAI provider ???? chat_completions ????????????? provider ?????
const (
	MonitorAPIModeChatCompletions = "chat_completions"
	MonitorAPIModeResponses       = "responses"
	MonitorAPIModeModels          = "models"
	MonitorAPIModeImages          = "images"
)

// ChannelMonitorLatestImage is the single most recent successful image
// generated by an images-mode monitor.
type ChannelMonitorLatestImage struct {
	MonitorID   int64
	ContentType string
	Data        []byte
	GeneratedAt time.Time
}

// ChannelMonitorLatestImageRepository is optional so existing repository test
// doubles and integrations do not need to grow their required interface.
type ChannelMonitorLatestImageRepository interface {
	UpsertLatestImage(ctx context.Context, image *ChannelMonitorLatestImage) error
	GetLatestImage(ctx context.Context, monitorID int64) (*ChannelMonitorLatestImage, error)
}

// ChannelMonitor ???????service ????????? ent ????
type ChannelMonitor struct {
	ID               int64
	Name             string
	Provider         string
	APIMode          string
	Endpoint         string
	SourceMode       string
	InternalAPIKeyID *int64
	InternalGroupID  *int64
	APIKey           string // ?????? API Key??? service ?????handler ???????????
	PrimaryModel     string
	ExtraModels      []string
	GroupName        string
	AccountGroupID   *int64
	Enabled          bool
	IntervalSeconds  int
	JitterSeconds    int // ???? ? [0, jitter] ?????????0 = ????
	// RequestTimeoutSeconds is the upper bound for one upstream health check.
	// Image generation uses this independently from its longer schedule interval.
	RequestTimeoutSeconds int
	LastCheckedAt         *time.Time
	CreatedBy             int64
	CreatedAt             time.Time
	UpdatedAt             time.Time

	// ?????????????? or ?????????????
	TemplateID       *int64            // ??? UI ?? + ??????????
	ExtraHeaders     map[string]string // ? adapter ?? headers ???????
	BodyOverrideMode string            // off / merge / replace
	BodyOverride     map[string]any    // ? mode != off ???

	// DuplicateOperationID is internal persistence metadata used to recover an
	// already committed duplicate after an ambiguous idempotency-store failure.
	// Repository implementations must keep it out of ExtraHeaders so it can
	// never be serialized to clients or forwarded to an upstream provider.
	DuplicateOperationID string

	// APIKeyDecryptFailed ?? APIKey ?????????????????
	// ?? APIKey ??????runner / RunCheck ?????????????
	APIKeyDecryptFailed bool
}

// ChannelMonitorListParams ?????????
type ChannelMonitorListParams struct {
	Page     int
	PageSize int
	Provider string
	Enabled  *bool
	Search   string
}

// ChannelMonitorCreateParams ?????
type ChannelMonitorCreateParams struct {
	Name                  string
	Provider              string
	APIMode               string
	Endpoint              string
	SourceMode            string
	InternalAPIKeyID      *int64
	InternalGroupID       *int64
	APIKey                string
	PrimaryModel          string
	ExtraModels           []string
	GroupName             string
	AccountGroupID        *int64
	Enabled               bool
	IntervalSeconds       int
	JitterSeconds         int
	RequestTimeoutSeconds int
	CreatedBy             int64
	TemplateID            *int64
	ExtraHeaders          map[string]string
	BodyOverrideMode      string
	BodyOverride          map[string]any
}

// ChannelMonitorUpdateParams ???????????"???????"??
type ChannelMonitorUpdateParams struct {
	Name             *string
	Provider         *string
	APIMode          *string
	Endpoint         *string
	SourceMode       *string
	InternalAPIKeyID *int64
	InternalGroupID  *int64
	APIKey           *string // ?????????????????
	PrimaryModel     *string
	ExtraModels      *[]string
	GroupName        *string
	// AccountGroupID is applied when non-nil. ClearAccountGroup explicitly
	// clears the binding because JSON null cannot preserve pointer tri-state.
	AccountGroupID        *int64
	ClearAccountGroup     bool
	Enabled               *bool
	IntervalSeconds       *int
	JitterSeconds         *int
	RequestTimeoutSeconds *int
	// ??????????? nil ??????? nil ??
	// TemplateID *(*int64)?? ** ?????nil=????&nil=???&&id=?? id?
	// ?????? ClearTemplate ???? + TemplateID??????
	TemplateID       *int64
	ClearTemplate    bool // true ??? TemplateID????? template_id ??
	ExtraHeaders     *map[string]string
	BodyOverrideMode *string
	BodyOverride     *map[string]any
}

// CheckResult ????????????
type CheckResult struct {
	Model            string
	Status           string // operational / degraded / failed / error
	LatencyMs        *int
	LatencyBreakdown *UsageLatencyBreakdown
	PingLatencyMs    *int
	AccountID        *int64
	AccountName      string
	ProbeMode        string // static / sticky / confirm / full
	CandidateCount   int
	HealthyCount     int
	Message          string
	CheckedAt        time.Time

	// Internal-only accounting metadata. It is intentionally kept out of
	// monitor history and API responses.
	monitorUsage            monitorUsage
	monitorRequestAttempted bool
	monitorCostRecorded     bool
	monitorCostModel        string
	monitorLatestImage      *monitorLatestImagePayload
}

// ChannelMonitorAccountProbeState is the durable selected account for one
// monitor/model pair. It is intentionally not exposed by user-facing APIs.
type ChannelMonitorAccountProbeState struct {
	MonitorID       int64
	Model           string
	AccountID       *int64
	AccountName     string
	FinalStatus     string
	LastLatencyMs   *int
	LastProbeMode   string
	LastFullSweepAt *time.Time
	LastCheckedAt   time.Time
	UpdatedAt       time.Time
}

// MonitorGroupCheckSummary is the best result selected from one grouped probe.
// It deliberately contains no credentials or request payload.
type MonitorGroupCheckSummary struct {
	GroupName       string
	CandidateCount  int
	SuccessfulCount int
	BestMonitorID   int64
	BestMonitorName string
	BestStatus      string
	BestLatencyMs   *int
}

// UserMonitorView ???????????????????? + 7d ??? + ??????????
type UserMonitorView struct {
	ID                      int64
	Name                    string
	Provider                string
	APIMode                 string
	GroupName               string
	AccountGroupID          *int64
	PrimaryModel            string
	PrimaryStatus           string
	PrimaryLatencyMs        *int
	PrimaryLatencyBreakdown *UsageLatencyBreakdown
	PrimaryPingLatencyMs    *int    // ??????? ping ??
	PrimarySource           string  // traffic / probe??????????
	Availability7d          float64 // 0-100
	ExtraModels             []ExtraModelStatus
	Timeline                []UserMonitorTimelinePoint // ????? N ?????? checked_at DESC??????
}

// UserMonitorTimelinePoint ???? timeline ??????? message ????????
type UserMonitorTimelinePoint struct {
	Status        string    `json:"status"`
	LatencyMs     *int      `json:"latency_ms"`
	PingLatencyMs *int      `json:"ping_latency_ms"`
	CheckedAt     time.Time `json:"checked_at"`
}

// ExtraModelStatus ???????????
type ExtraModelStatus struct {
	Model            string
	Status           string
	LatencyMs        *int
	LatencyBreakdown *UsageLatencyBreakdown
	Source           string
	Availability7d   float64
}

// UserMonitorDetail ????????????????? 7d/15d/30d ??????????
type UserMonitorDetail struct {
	ID        int64
	Name      string
	Provider  string
	GroupName string
	Models    []ModelDetail
}

// ModelDetail ????????/?????
type ModelDetail struct {
	Model                  string
	LatestStatus           string
	LatestLatencyMs        *int
	LatestLatencyBreakdown *UsageLatencyBreakdown
	Source                 string
	Availability7d         float64 // 0-100
	Availability15d        float64
	Availability30d        float64
	AvgLatency7dMs         *int
}

// ChannelMonitorHistoryRow ????????service ?? repository ???????
type ChannelMonitorHistoryRow struct {
	MonitorID        int64
	Model            string
	Status           string
	LatencyMs        *int
	LatencyBreakdown *UsageLatencyBreakdown
	PingLatencyMs    *int
	AccountID        *int64
	AccountName      string
	ProbeMode        string
	CandidateCount   int
	HealthyCount     int
	Message          string
	CheckedAt        time.Time
}

// ChannelMonitorHistoryEntry ??????????? ent ?? ID??
type ChannelMonitorHistoryEntry struct {
	ID               int64
	Model            string
	Status           string
	LatencyMs        *int
	LatencyBreakdown *UsageLatencyBreakdown
	PingLatencyMs    *int
	AccountID        *int64
	AccountName      string
	ProbeMode        string
	CandidateCount   int
	HealthyCount     int
	Message          string
	CheckedAt        time.Time
}

// ChannelMonitorLatest ?????????????? UserMonitorView ????
type ChannelMonitorLatest struct {
	Model            string
	Status           string
	LatencyMs        *int
	LatencyBreakdown *UsageLatencyBreakdown
	PingLatencyMs    *int
	AccountID        *int64
	AccountName      string
	ProbeMode        string
	CandidateCount   int
	HealthyCount     int
	CheckedAt        time.Time
}

// ChannelMonitorAvailability ????????????????????? UserMonitorDetail ????
type ChannelMonitorAvailability struct {
	Model             string
	WindowDays        int
	TotalChecks       int
	OperationalChecks int // operational + degraded ????
	AvailabilityPct   float64
	AvgLatencyMs      *int
}

// MonitorStatusSummary ???????admin list ???? repo ?????? N+1??
// PrimaryStatus / PrimaryLatencyMs ??????????Availability7d ???? 7 ?????
// ExtraModels ????????????? hover ????
type MonitorStatusSummary struct {
	PrimaryStatus           string // ?????????
	PrimaryLatencyMs        *int
	PrimaryLatencyBreakdown *UsageLatencyBreakdown
	PrimaryAccountID        *int64
	PrimaryAccountName      string
	PrimaryProbeMode        string
	PrimaryCandidateCount   int
	PrimaryHealthyCount     int
	PrimaryCheckedAt        time.Time
	Availability7d          float64 // 0-100?????? 0
	ExtraModels             []ExtraModelStatus
}
