// Code generated by ent, DO NOT EDIT.

package subscriptionpurchase

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the subscriptionpurchase type in the database.
	Label = "subscription_purchase"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPlanID holds the string denoting the plan_id field in the database.
	FieldPlanID = "plan_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTierCode holds the string denoting the tier_code field in the database.
	FieldTierCode = "tier_code"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldStartsAt holds the string denoting the starts_at field in the database.
	FieldStartsAt = "starts_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldConcurrencyEntitlement holds the string denoting the concurrency_entitlement field in the database.
	FieldConcurrencyEntitlement = "concurrency_entitlement"
	// FieldLifetimeQuotaUsd holds the string denoting the lifetime_quota_usd field in the database.
	FieldLifetimeQuotaUsd = "lifetime_quota_usd"
	// FieldDailyQuotaUsd holds the string denoting the daily_quota_usd field in the database.
	FieldDailyQuotaUsd = "daily_quota_usd"
	// FieldWeeklyQuotaUsd holds the string denoting the weekly_quota_usd field in the database.
	FieldWeeklyQuotaUsd = "weekly_quota_usd"
	// FieldMonthlyQuotaUsd holds the string denoting the monthly_quota_usd field in the database.
	FieldMonthlyQuotaUsd = "monthly_quota_usd"
	// FieldLifetimeUsageUsd holds the string denoting the lifetime_usage_usd field in the database.
	FieldLifetimeUsageUsd = "lifetime_usage_usd"
	// FieldDailyUsageUsd holds the string denoting the daily_usage_usd field in the database.
	FieldDailyUsageUsd = "daily_usage_usd"
	// FieldWeeklyUsageUsd holds the string denoting the weekly_usage_usd field in the database.
	FieldWeeklyUsageUsd = "weekly_usage_usd"
	// FieldMonthlyUsageUsd holds the string denoting the monthly_usage_usd field in the database.
	FieldMonthlyUsageUsd = "monthly_usage_usd"
	// FieldDailyWindowStart holds the string denoting the daily_window_start field in the database.
	FieldDailyWindowStart = "daily_window_start"
	// FieldWeeklyWindowStart holds the string denoting the weekly_window_start field in the database.
	FieldWeeklyWindowStart = "weekly_window_start"
	// FieldMonthlyWindowStart holds the string denoting the monthly_window_start field in the database.
	FieldMonthlyWindowStart = "monthly_window_start"
	// FieldBalanceTopupEnabled holds the string denoting the balance_topup_enabled field in the database.
	FieldBalanceTopupEnabled = "balance_topup_enabled"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldSourceID holds the string denoting the source_id field in the database.
	FieldSourceID = "source_id"
	// FieldSnapshot holds the string denoting the snapshot field in the database.
	FieldSnapshot = "snapshot"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeGroups holds the string denoting the groups edge name in mutations.
	EdgeGroups = "groups"
	// Table holds the table name of the subscriptionpurchase in the database.
	Table = "subscription_purchases"
	// GroupsTable is the table that holds the groups relation/edge.
	GroupsTable = "subscription_purchase_groups"
	// GroupsInverseTable is the table name for the SubscriptionPurchaseGroup entity.
	// It exists in this package in order to avoid circular dependency with the "subscriptionpurchasegroup" package.
	GroupsInverseTable = "subscription_purchase_groups"
	// GroupsColumn is the table column denoting the groups relation/edge.
	GroupsColumn = "purchase_id"
)

// Columns holds all SQL columns for subscriptionpurchase fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldPlanID,
	FieldName,
	FieldTierCode,
	FieldPrice,
	FieldCurrency,
	FieldStartsAt,
	FieldExpiresAt,
	FieldStatus,
	FieldConcurrencyEntitlement,
	FieldLifetimeQuotaUsd,
	FieldDailyQuotaUsd,
	FieldWeeklyQuotaUsd,
	FieldMonthlyQuotaUsd,
	FieldLifetimeUsageUsd,
	FieldDailyUsageUsd,
	FieldWeeklyUsageUsd,
	FieldMonthlyUsageUsd,
	FieldDailyWindowStart,
	FieldWeeklyWindowStart,
	FieldMonthlyWindowStart,
	FieldBalanceTopupEnabled,
	FieldSource,
	FieldSourceID,
	FieldSnapshot,
	FieldNotes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultTierCode holds the default value on creation for the "tier_code" field.
	DefaultTierCode string
	// TierCodeValidator is a validator for the "tier_code" field. It is called by the builders before save.
	TierCodeValidator func(string) error
	// DefaultPrice holds the default value on creation for the "price" field.
	DefaultPrice float64
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultConcurrencyEntitlement holds the default value on creation for the "concurrency_entitlement" field.
	DefaultConcurrencyEntitlement int
	// DefaultLifetimeQuotaUsd holds the default value on creation for the "lifetime_quota_usd" field.
	DefaultLifetimeQuotaUsd float64
	// DefaultDailyQuotaUsd holds the default value on creation for the "daily_quota_usd" field.
	DefaultDailyQuotaUsd float64
	// DefaultWeeklyQuotaUsd holds the default value on creation for the "weekly_quota_usd" field.
	DefaultWeeklyQuotaUsd float64
	// DefaultMonthlyQuotaUsd holds the default value on creation for the "monthly_quota_usd" field.
	DefaultMonthlyQuotaUsd float64
	// DefaultLifetimeUsageUsd holds the default value on creation for the "lifetime_usage_usd" field.
	DefaultLifetimeUsageUsd float64
	// DefaultDailyUsageUsd holds the default value on creation for the "daily_usage_usd" field.
	DefaultDailyUsageUsd float64
	// DefaultWeeklyUsageUsd holds the default value on creation for the "weekly_usage_usd" field.
	DefaultWeeklyUsageUsd float64
	// DefaultMonthlyUsageUsd holds the default value on creation for the "monthly_usage_usd" field.
	DefaultMonthlyUsageUsd float64
	// DefaultBalanceTopupEnabled holds the default value on creation for the "balance_topup_enabled" field.
	DefaultBalanceTopupEnabled bool
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the SubscriptionPurchase queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPlanID orders the results by the plan_id field.
func ByPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByTierCode orders the results by the tier_code field.
func ByTierCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTierCode, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByStartsAt orders the results by the starts_at field.
func ByStartsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartsAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByConcurrencyEntitlement orders the results by the concurrency_entitlement field.
func ByConcurrencyEntitlement(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConcurrencyEntitlement, opts...).ToFunc()
}

// ByLifetimeQuotaUsd orders the results by the lifetime_quota_usd field.
func ByLifetimeQuotaUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLifetimeQuotaUsd, opts...).ToFunc()
}

// ByDailyQuotaUsd orders the results by the daily_quota_usd field.
func ByDailyQuotaUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyQuotaUsd, opts...).ToFunc()
}

// ByWeeklyQuotaUsd orders the results by the weekly_quota_usd field.
func ByWeeklyQuotaUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyQuotaUsd, opts...).ToFunc()
}

// ByMonthlyQuotaUsd orders the results by the monthly_quota_usd field.
func ByMonthlyQuotaUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyQuotaUsd, opts...).ToFunc()
}

// ByLifetimeUsageUsd orders the results by the lifetime_usage_usd field.
func ByLifetimeUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLifetimeUsageUsd, opts...).ToFunc()
}

// ByDailyUsageUsd orders the results by the daily_usage_usd field.
func ByDailyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyUsageUsd, opts...).ToFunc()
}

// ByWeeklyUsageUsd orders the results by the weekly_usage_usd field.
func ByWeeklyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyUsageUsd, opts...).ToFunc()
}

// ByMonthlyUsageUsd orders the results by the monthly_usage_usd field.
func ByMonthlyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyUsageUsd, opts...).ToFunc()
}

// ByDailyWindowStart orders the results by the daily_window_start field.
func ByDailyWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyWindowStart, opts...).ToFunc()
}

// ByWeeklyWindowStart orders the results by the weekly_window_start field.
func ByWeeklyWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyWindowStart, opts...).ToFunc()
}

// ByMonthlyWindowStart orders the results by the monthly_window_start field.
func ByMonthlyWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyWindowStart, opts...).ToFunc()
}

// ByBalanceTopupEnabled orders the results by the balance_topup_enabled field.
func ByBalanceTopupEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceTopupEnabled, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// BySourceID orders the results by the source_id field.
func BySourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceID, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGroupsCount orders the results by groups count.
func ByGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGroupsStep(), opts...)
	}
}

// ByGroups orders the results by groups terms.
func ByGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GroupsTable, GroupsColumn),
	)
}
