// Code generated by ent, DO NOT EDIT.

package subscriptionpurchase

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldUserID, v))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldPlanID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldName, v))
}

// TierCode applies equality check predicate on the "tier_code" field. It's identical to TierCodeEQ.
func TierCode(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldTierCode, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldPrice, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldCurrency, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldStartsAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldExpiresAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldStatus, v))
}

// ConcurrencyEntitlement applies equality check predicate on the "concurrency_entitlement" field. It's identical to ConcurrencyEntitlementEQ.
func ConcurrencyEntitlement(v int) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldConcurrencyEntitlement, v))
}

// LifetimeQuotaUsd applies equality check predicate on the "lifetime_quota_usd" field. It's identical to LifetimeQuotaUsdEQ.
func LifetimeQuotaUsd(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldLifetimeQuotaUsd, v))
}

// DailyQuotaUsd applies equality check predicate on the "daily_quota_usd" field. It's identical to DailyQuotaUsdEQ.
func DailyQuotaUsd(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldDailyQuotaUsd, v))
}

// WeeklyQuotaUsd applies equality check predicate on the "weekly_quota_usd" field. It's identical to WeeklyQuotaUsdEQ.
func WeeklyQuotaUsd(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldWeeklyQuotaUsd, v))
}

// MonthlyQuotaUsd applies equality check predicate on the "monthly_quota_usd" field. It's identical to MonthlyQuotaUsdEQ.
func MonthlyQuotaUsd(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldMonthlyQuotaUsd, v))
}

// LifetimeUsageUsd applies equality check predicate on the "lifetime_usage_usd" field. It's identical to LifetimeUsageUsdEQ.
func LifetimeUsageUsd(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldLifetimeUsageUsd, v))
}

// DailyUsageUsd applies equality check predicate on the "daily_usage_usd" field. It's identical to DailyUsageUsdEQ.
func DailyUsageUsd(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldDailyUsageUsd, v))
}

// WeeklyUsageUsd applies equality check predicate on the "weekly_usage_usd" field. It's identical to WeeklyUsageUsdEQ.
func WeeklyUsageUsd(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldWeeklyUsageUsd, v))
}

// MonthlyUsageUsd applies equality check predicate on the "monthly_usage_usd" field. It's identical to MonthlyUsageUsdEQ.
func MonthlyUsageUsd(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldMonthlyUsageUsd, v))
}

// DailyWindowStart applies equality check predicate on the "daily_window_start" field. It's identical to DailyWindowStartEQ.
func DailyWindowStart(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldDailyWindowStart, v))
}

// WeeklyWindowStart applies equality check predicate on the "weekly_window_start" field. It's identical to WeeklyWindowStartEQ.
func WeeklyWindowStart(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldWeeklyWindowStart, v))
}

// MonthlyWindowStart applies equality check predicate on the "monthly_window_start" field. It's identical to MonthlyWindowStartEQ.
func MonthlyWindowStart(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldMonthlyWindowStart, v))
}

// BalanceTopupEnabled applies equality check predicate on the "balance_topup_enabled" field. It's identical to BalanceTopupEnabledEQ.
func BalanceTopupEnabled(v bool) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldBalanceTopupEnabled, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldSource, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldSourceID, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldUserID, v))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldPlanID, vs...))
}

// PlanIDGT applies the GT predicate on the "plan_id" field.
func PlanIDGT(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldPlanID, v))
}

// PlanIDGTE applies the GTE predicate on the "plan_id" field.
func PlanIDGTE(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldPlanID, v))
}

// PlanIDLT applies the LT predicate on the "plan_id" field.
func PlanIDLT(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldPlanID, v))
}

// PlanIDLTE applies the LTE predicate on the "plan_id" field.
func PlanIDLTE(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldPlanID, v))
}

// PlanIDIsNil applies the IsNil predicate on the "plan_id" field.
func PlanIDIsNil() predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIsNull(FieldPlanID))
}

// PlanIDNotNil applies the NotNil predicate on the "plan_id" field.
func PlanIDNotNil() predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotNull(FieldPlanID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldContainsFold(FieldName, v))
}

// TierCodeEQ applies the EQ predicate on the "tier_code" field.
func TierCodeEQ(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldTierCode, v))
}

// TierCodeNEQ applies the NEQ predicate on the "tier_code" field.
func TierCodeNEQ(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldTierCode, v))
}

// TierCodeIn applies the In predicate on the "tier_code" field.
func TierCodeIn(vs ...string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldTierCode, vs...))
}

// TierCodeNotIn applies the NotIn predicate on the "tier_code" field.
func TierCodeNotIn(vs ...string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldTierCode, vs...))
}

// TierCodeGT applies the GT predicate on the "tier_code" field.
func TierCodeGT(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldTierCode, v))
}

// TierCodeGTE applies the GTE predicate on the "tier_code" field.
func TierCodeGTE(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldTierCode, v))
}

// TierCodeLT applies the LT predicate on the "tier_code" field.
func TierCodeLT(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldTierCode, v))
}

// TierCodeLTE applies the LTE predicate on the "tier_code" field.
func TierCodeLTE(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldTierCode, v))
}

// TierCodeContains applies the Contains predicate on the "tier_code" field.
func TierCodeContains(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldContains(FieldTierCode, v))
}

// TierCodeHasPrefix applies the HasPrefix predicate on the "tier_code" field.
func TierCodeHasPrefix(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldHasPrefix(FieldTierCode, v))
}

// TierCodeHasSuffix applies the HasSuffix predicate on the "tier_code" field.
func TierCodeHasSuffix(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldHasSuffix(FieldTierCode, v))
}

// TierCodeEqualFold applies the EqualFold predicate on the "tier_code" field.
func TierCodeEqualFold(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEqualFold(FieldTierCode, v))
}

// TierCodeContainsFold applies the ContainsFold predicate on the "tier_code" field.
func TierCodeContainsFold(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldContainsFold(FieldTierCode, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldPrice, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldContainsFold(FieldCurrency, v))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldStartsAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldExpiresAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldContainsFold(FieldStatus, v))
}

// ConcurrencyEntitlementEQ applies the EQ predicate on the "concurrency_entitlement" field.
func ConcurrencyEntitlementEQ(v int) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldConcurrencyEntitlement, v))
}

// ConcurrencyEntitlementNEQ applies the NEQ predicate on the "concurrency_entitlement" field.
func ConcurrencyEntitlementNEQ(v int) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldConcurrencyEntitlement, v))
}

// ConcurrencyEntitlementIn applies the In predicate on the "concurrency_entitlement" field.
func ConcurrencyEntitlementIn(vs ...int) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldConcurrencyEntitlement, vs...))
}

// ConcurrencyEntitlementNotIn applies the NotIn predicate on the "concurrency_entitlement" field.
func ConcurrencyEntitlementNotIn(vs ...int) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldConcurrencyEntitlement, vs...))
}

// ConcurrencyEntitlementGT applies the GT predicate on the "concurrency_entitlement" field.
func ConcurrencyEntitlementGT(v int) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldConcurrencyEntitlement, v))
}

// ConcurrencyEntitlementGTE applies the GTE predicate on the "concurrency_entitlement" field.
func ConcurrencyEntitlementGTE(v int) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldConcurrencyEntitlement, v))
}

// ConcurrencyEntitlementLT applies the LT predicate on the "concurrency_entitlement" field.
func ConcurrencyEntitlementLT(v int) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldConcurrencyEntitlement, v))
}

// ConcurrencyEntitlementLTE applies the LTE predicate on the "concurrency_entitlement" field.
func ConcurrencyEntitlementLTE(v int) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldConcurrencyEntitlement, v))
}

// LifetimeQuotaUsdEQ applies the EQ predicate on the "lifetime_quota_usd" field.
func LifetimeQuotaUsdEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldLifetimeQuotaUsd, v))
}

// LifetimeQuotaUsdNEQ applies the NEQ predicate on the "lifetime_quota_usd" field.
func LifetimeQuotaUsdNEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldLifetimeQuotaUsd, v))
}

// LifetimeQuotaUsdIn applies the In predicate on the "lifetime_quota_usd" field.
func LifetimeQuotaUsdIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldLifetimeQuotaUsd, vs...))
}

// LifetimeQuotaUsdNotIn applies the NotIn predicate on the "lifetime_quota_usd" field.
func LifetimeQuotaUsdNotIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldLifetimeQuotaUsd, vs...))
}

// LifetimeQuotaUsdGT applies the GT predicate on the "lifetime_quota_usd" field.
func LifetimeQuotaUsdGT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldLifetimeQuotaUsd, v))
}

// LifetimeQuotaUsdGTE applies the GTE predicate on the "lifetime_quota_usd" field.
func LifetimeQuotaUsdGTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldLifetimeQuotaUsd, v))
}

// LifetimeQuotaUsdLT applies the LT predicate on the "lifetime_quota_usd" field.
func LifetimeQuotaUsdLT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldLifetimeQuotaUsd, v))
}

// LifetimeQuotaUsdLTE applies the LTE predicate on the "lifetime_quota_usd" field.
func LifetimeQuotaUsdLTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldLifetimeQuotaUsd, v))
}

// DailyQuotaUsdEQ applies the EQ predicate on the "daily_quota_usd" field.
func DailyQuotaUsdEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldDailyQuotaUsd, v))
}

// DailyQuotaUsdNEQ applies the NEQ predicate on the "daily_quota_usd" field.
func DailyQuotaUsdNEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldDailyQuotaUsd, v))
}

// DailyQuotaUsdIn applies the In predicate on the "daily_quota_usd" field.
func DailyQuotaUsdIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldDailyQuotaUsd, vs...))
}

// DailyQuotaUsdNotIn applies the NotIn predicate on the "daily_quota_usd" field.
func DailyQuotaUsdNotIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldDailyQuotaUsd, vs...))
}

// DailyQuotaUsdGT applies the GT predicate on the "daily_quota_usd" field.
func DailyQuotaUsdGT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldDailyQuotaUsd, v))
}

// DailyQuotaUsdGTE applies the GTE predicate on the "daily_quota_usd" field.
func DailyQuotaUsdGTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldDailyQuotaUsd, v))
}

// DailyQuotaUsdLT applies the LT predicate on the "daily_quota_usd" field.
func DailyQuotaUsdLT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldDailyQuotaUsd, v))
}

// DailyQuotaUsdLTE applies the LTE predicate on the "daily_quota_usd" field.
func DailyQuotaUsdLTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldDailyQuotaUsd, v))
}

// WeeklyQuotaUsdEQ applies the EQ predicate on the "weekly_quota_usd" field.
func WeeklyQuotaUsdEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldWeeklyQuotaUsd, v))
}

// WeeklyQuotaUsdNEQ applies the NEQ predicate on the "weekly_quota_usd" field.
func WeeklyQuotaUsdNEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldWeeklyQuotaUsd, v))
}

// WeeklyQuotaUsdIn applies the In predicate on the "weekly_quota_usd" field.
func WeeklyQuotaUsdIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldWeeklyQuotaUsd, vs...))
}

// WeeklyQuotaUsdNotIn applies the NotIn predicate on the "weekly_quota_usd" field.
func WeeklyQuotaUsdNotIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldWeeklyQuotaUsd, vs...))
}

// WeeklyQuotaUsdGT applies the GT predicate on the "weekly_quota_usd" field.
func WeeklyQuotaUsdGT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldWeeklyQuotaUsd, v))
}

// WeeklyQuotaUsdGTE applies the GTE predicate on the "weekly_quota_usd" field.
func WeeklyQuotaUsdGTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldWeeklyQuotaUsd, v))
}

// WeeklyQuotaUsdLT applies the LT predicate on the "weekly_quota_usd" field.
func WeeklyQuotaUsdLT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldWeeklyQuotaUsd, v))
}

// WeeklyQuotaUsdLTE applies the LTE predicate on the "weekly_quota_usd" field.
func WeeklyQuotaUsdLTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldWeeklyQuotaUsd, v))
}

// MonthlyQuotaUsdEQ applies the EQ predicate on the "monthly_quota_usd" field.
func MonthlyQuotaUsdEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldMonthlyQuotaUsd, v))
}

// MonthlyQuotaUsdNEQ applies the NEQ predicate on the "monthly_quota_usd" field.
func MonthlyQuotaUsdNEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldMonthlyQuotaUsd, v))
}

// MonthlyQuotaUsdIn applies the In predicate on the "monthly_quota_usd" field.
func MonthlyQuotaUsdIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldMonthlyQuotaUsd, vs...))
}

// MonthlyQuotaUsdNotIn applies the NotIn predicate on the "monthly_quota_usd" field.
func MonthlyQuotaUsdNotIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldMonthlyQuotaUsd, vs...))
}

// MonthlyQuotaUsdGT applies the GT predicate on the "monthly_quota_usd" field.
func MonthlyQuotaUsdGT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldMonthlyQuotaUsd, v))
}

// MonthlyQuotaUsdGTE applies the GTE predicate on the "monthly_quota_usd" field.
func MonthlyQuotaUsdGTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldMonthlyQuotaUsd, v))
}

// MonthlyQuotaUsdLT applies the LT predicate on the "monthly_quota_usd" field.
func MonthlyQuotaUsdLT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldMonthlyQuotaUsd, v))
}

// MonthlyQuotaUsdLTE applies the LTE predicate on the "monthly_quota_usd" field.
func MonthlyQuotaUsdLTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldMonthlyQuotaUsd, v))
}

// LifetimeUsageUsdEQ applies the EQ predicate on the "lifetime_usage_usd" field.
func LifetimeUsageUsdEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldLifetimeUsageUsd, v))
}

// LifetimeUsageUsdNEQ applies the NEQ predicate on the "lifetime_usage_usd" field.
func LifetimeUsageUsdNEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldLifetimeUsageUsd, v))
}

// LifetimeUsageUsdIn applies the In predicate on the "lifetime_usage_usd" field.
func LifetimeUsageUsdIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldLifetimeUsageUsd, vs...))
}

// LifetimeUsageUsdNotIn applies the NotIn predicate on the "lifetime_usage_usd" field.
func LifetimeUsageUsdNotIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldLifetimeUsageUsd, vs...))
}

// LifetimeUsageUsdGT applies the GT predicate on the "lifetime_usage_usd" field.
func LifetimeUsageUsdGT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldLifetimeUsageUsd, v))
}

// LifetimeUsageUsdGTE applies the GTE predicate on the "lifetime_usage_usd" field.
func LifetimeUsageUsdGTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldLifetimeUsageUsd, v))
}

// LifetimeUsageUsdLT applies the LT predicate on the "lifetime_usage_usd" field.
func LifetimeUsageUsdLT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldLifetimeUsageUsd, v))
}

// LifetimeUsageUsdLTE applies the LTE predicate on the "lifetime_usage_usd" field.
func LifetimeUsageUsdLTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldLifetimeUsageUsd, v))
}

// DailyUsageUsdEQ applies the EQ predicate on the "daily_usage_usd" field.
func DailyUsageUsdEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldDailyUsageUsd, v))
}

// DailyUsageUsdNEQ applies the NEQ predicate on the "daily_usage_usd" field.
func DailyUsageUsdNEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldDailyUsageUsd, v))
}

// DailyUsageUsdIn applies the In predicate on the "daily_usage_usd" field.
func DailyUsageUsdIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldDailyUsageUsd, vs...))
}

// DailyUsageUsdNotIn applies the NotIn predicate on the "daily_usage_usd" field.
func DailyUsageUsdNotIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldDailyUsageUsd, vs...))
}

// DailyUsageUsdGT applies the GT predicate on the "daily_usage_usd" field.
func DailyUsageUsdGT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldDailyUsageUsd, v))
}

// DailyUsageUsdGTE applies the GTE predicate on the "daily_usage_usd" field.
func DailyUsageUsdGTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldDailyUsageUsd, v))
}

// DailyUsageUsdLT applies the LT predicate on the "daily_usage_usd" field.
func DailyUsageUsdLT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldDailyUsageUsd, v))
}

// DailyUsageUsdLTE applies the LTE predicate on the "daily_usage_usd" field.
func DailyUsageUsdLTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldDailyUsageUsd, v))
}

// WeeklyUsageUsdEQ applies the EQ predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdNEQ applies the NEQ predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdNEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdIn applies the In predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldWeeklyUsageUsd, vs...))
}

// WeeklyUsageUsdNotIn applies the NotIn predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdNotIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldWeeklyUsageUsd, vs...))
}

// WeeklyUsageUsdGT applies the GT predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdGT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdGTE applies the GTE predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdGTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdLT applies the LT predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdLT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdLTE applies the LTE predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdLTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldWeeklyUsageUsd, v))
}

// MonthlyUsageUsdEQ applies the EQ predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdNEQ applies the NEQ predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdNEQ(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdIn applies the In predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldMonthlyUsageUsd, vs...))
}

// MonthlyUsageUsdNotIn applies the NotIn predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdNotIn(vs ...float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldMonthlyUsageUsd, vs...))
}

// MonthlyUsageUsdGT applies the GT predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdGT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdGTE applies the GTE predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdGTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdLT applies the LT predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdLT(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdLTE applies the LTE predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdLTE(v float64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldMonthlyUsageUsd, v))
}

// DailyWindowStartEQ applies the EQ predicate on the "daily_window_start" field.
func DailyWindowStartEQ(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldDailyWindowStart, v))
}

// DailyWindowStartNEQ applies the NEQ predicate on the "daily_window_start" field.
func DailyWindowStartNEQ(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldDailyWindowStart, v))
}

// DailyWindowStartIn applies the In predicate on the "daily_window_start" field.
func DailyWindowStartIn(vs ...time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldDailyWindowStart, vs...))
}

// DailyWindowStartNotIn applies the NotIn predicate on the "daily_window_start" field.
func DailyWindowStartNotIn(vs ...time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldDailyWindowStart, vs...))
}

// DailyWindowStartGT applies the GT predicate on the "daily_window_start" field.
func DailyWindowStartGT(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldDailyWindowStart, v))
}

// DailyWindowStartGTE applies the GTE predicate on the "daily_window_start" field.
func DailyWindowStartGTE(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldDailyWindowStart, v))
}

// DailyWindowStartLT applies the LT predicate on the "daily_window_start" field.
func DailyWindowStartLT(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldDailyWindowStart, v))
}

// DailyWindowStartLTE applies the LTE predicate on the "daily_window_start" field.
func DailyWindowStartLTE(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldDailyWindowStart, v))
}

// DailyWindowStartIsNil applies the IsNil predicate on the "daily_window_start" field.
func DailyWindowStartIsNil() predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIsNull(FieldDailyWindowStart))
}

// DailyWindowStartNotNil applies the NotNil predicate on the "daily_window_start" field.
func DailyWindowStartNotNil() predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotNull(FieldDailyWindowStart))
}

// WeeklyWindowStartEQ applies the EQ predicate on the "weekly_window_start" field.
func WeeklyWindowStartEQ(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartNEQ applies the NEQ predicate on the "weekly_window_start" field.
func WeeklyWindowStartNEQ(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartIn applies the In predicate on the "weekly_window_start" field.
func WeeklyWindowStartIn(vs ...time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldWeeklyWindowStart, vs...))
}

// WeeklyWindowStartNotIn applies the NotIn predicate on the "weekly_window_start" field.
func WeeklyWindowStartNotIn(vs ...time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldWeeklyWindowStart, vs...))
}

// WeeklyWindowStartGT applies the GT predicate on the "weekly_window_start" field.
func WeeklyWindowStartGT(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartGTE applies the GTE predicate on the "weekly_window_start" field.
func WeeklyWindowStartGTE(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartLT applies the LT predicate on the "weekly_window_start" field.
func WeeklyWindowStartLT(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartLTE applies the LTE predicate on the "weekly_window_start" field.
func WeeklyWindowStartLTE(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartIsNil applies the IsNil predicate on the "weekly_window_start" field.
func WeeklyWindowStartIsNil() predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIsNull(FieldWeeklyWindowStart))
}

// WeeklyWindowStartNotNil applies the NotNil predicate on the "weekly_window_start" field.
func WeeklyWindowStartNotNil() predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotNull(FieldWeeklyWindowStart))
}

// MonthlyWindowStartEQ applies the EQ predicate on the "monthly_window_start" field.
func MonthlyWindowStartEQ(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartNEQ applies the NEQ predicate on the "monthly_window_start" field.
func MonthlyWindowStartNEQ(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartIn applies the In predicate on the "monthly_window_start" field.
func MonthlyWindowStartIn(vs ...time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldMonthlyWindowStart, vs...))
}

// MonthlyWindowStartNotIn applies the NotIn predicate on the "monthly_window_start" field.
func MonthlyWindowStartNotIn(vs ...time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldMonthlyWindowStart, vs...))
}

// MonthlyWindowStartGT applies the GT predicate on the "monthly_window_start" field.
func MonthlyWindowStartGT(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartGTE applies the GTE predicate on the "monthly_window_start" field.
func MonthlyWindowStartGTE(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartLT applies the LT predicate on the "monthly_window_start" field.
func MonthlyWindowStartLT(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartLTE applies the LTE predicate on the "monthly_window_start" field.
func MonthlyWindowStartLTE(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartIsNil applies the IsNil predicate on the "monthly_window_start" field.
func MonthlyWindowStartIsNil() predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIsNull(FieldMonthlyWindowStart))
}

// MonthlyWindowStartNotNil applies the NotNil predicate on the "monthly_window_start" field.
func MonthlyWindowStartNotNil() predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotNull(FieldMonthlyWindowStart))
}

// BalanceTopupEnabledEQ applies the EQ predicate on the "balance_topup_enabled" field.
func BalanceTopupEnabledEQ(v bool) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldBalanceTopupEnabled, v))
}

// BalanceTopupEnabledNEQ applies the NEQ predicate on the "balance_topup_enabled" field.
func BalanceTopupEnabledNEQ(v bool) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldBalanceTopupEnabled, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldContainsFold(FieldSource, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v int64) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDIsNil applies the IsNil predicate on the "source_id" field.
func SourceIDIsNil() predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIsNull(FieldSourceID))
}

// SourceIDNotNil applies the NotNil predicate on the "source_id" field.
func SourceIDNotNil() predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotNull(FieldSourceID))
}

// SnapshotIsNil applies the IsNil predicate on the "snapshot" field.
func SnapshotIsNil() predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIsNull(FieldSnapshot))
}

// SnapshotNotNil applies the NotNil predicate on the "snapshot" field.
func SnapshotNotNil() predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotNull(FieldSnapshot))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GroupsTable, GroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.SubscriptionPurchaseGroup) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionPurchase) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionPurchase) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionPurchase) predicate.SubscriptionPurchase {
	return predicate.SubscriptionPurchase(sql.NotPredicates(p))
}
