// Code generated by ent, DO NOT EDIT.

package subscriptionpurchasegroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the subscriptionpurchasegroup type in the database.
	Label = "subscription_purchase_group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPurchaseID holds the string denoting the purchase_id field in the database.
	FieldPurchaseID = "purchase_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldGroupName holds the string denoting the group_name field in the database.
	FieldGroupName = "group_name"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgePurchase holds the string denoting the purchase edge name in mutations.
	EdgePurchase = "purchase"
	// Table holds the table name of the subscriptionpurchasegroup in the database.
	Table = "subscription_purchase_groups"
	// PurchaseTable is the table that holds the purchase relation/edge.
	PurchaseTable = "subscription_purchase_groups"
	// PurchaseInverseTable is the table name for the SubscriptionPurchase entity.
	// It exists in this package in order to avoid circular dependency with the "subscriptionpurchase" package.
	PurchaseInverseTable = "subscription_purchases"
	// PurchaseColumn is the table column denoting the purchase relation/edge.
	PurchaseColumn = "purchase_id"
)

// Columns holds all SQL columns for subscriptionpurchasegroup fields.
var Columns = []string{
	FieldID,
	FieldPurchaseID,
	FieldGroupID,
	FieldGroupName,
	FieldPlatform,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultGroupName holds the default value on creation for the "group_name" field.
	DefaultGroupName string
	// GroupNameValidator is a validator for the "group_name" field. It is called by the builders before save.
	GroupNameValidator func(string) error
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the SubscriptionPurchaseGroup queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPurchaseID orders the results by the purchase_id field.
func ByPurchaseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurchaseID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByGroupName orders the results by the group_name field.
func ByGroupName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupName, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByPurchaseField orders the results by purchase field.
func ByPurchaseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPurchaseStep(), sql.OrderByField(field, opts...))
	}
}
func newPurchaseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PurchaseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PurchaseTable, PurchaseColumn),
	)
}
