// Code generated by ent, DO NOT EDIT.

package subscriptionpurchasegroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldLTE(FieldID, id))
}

// PurchaseID applies equality check predicate on the "purchase_id" field. It's identical to PurchaseIDEQ.
func PurchaseID(v int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldEQ(FieldPurchaseID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldEQ(FieldGroupID, v))
}

// GroupName applies equality check predicate on the "group_name" field. It's identical to GroupNameEQ.
func GroupName(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldEQ(FieldGroupName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldEQ(FieldPlatform, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// PurchaseIDEQ applies the EQ predicate on the "purchase_id" field.
func PurchaseIDEQ(v int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldEQ(FieldPurchaseID, v))
}

// PurchaseIDNEQ applies the NEQ predicate on the "purchase_id" field.
func PurchaseIDNEQ(v int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldNEQ(FieldPurchaseID, v))
}

// PurchaseIDIn applies the In predicate on the "purchase_id" field.
func PurchaseIDIn(vs ...int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldIn(FieldPurchaseID, vs...))
}

// PurchaseIDNotIn applies the NotIn predicate on the "purchase_id" field.
func PurchaseIDNotIn(vs ...int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldNotIn(FieldPurchaseID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldLTE(FieldGroupID, v))
}

// GroupNameEQ applies the EQ predicate on the "group_name" field.
func GroupNameEQ(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldEQ(FieldGroupName, v))
}

// GroupNameNEQ applies the NEQ predicate on the "group_name" field.
func GroupNameNEQ(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldNEQ(FieldGroupName, v))
}

// GroupNameIn applies the In predicate on the "group_name" field.
func GroupNameIn(vs ...string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldIn(FieldGroupName, vs...))
}

// GroupNameNotIn applies the NotIn predicate on the "group_name" field.
func GroupNameNotIn(vs ...string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldNotIn(FieldGroupName, vs...))
}

// GroupNameGT applies the GT predicate on the "group_name" field.
func GroupNameGT(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldGT(FieldGroupName, v))
}

// GroupNameGTE applies the GTE predicate on the "group_name" field.
func GroupNameGTE(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldGTE(FieldGroupName, v))
}

// GroupNameLT applies the LT predicate on the "group_name" field.
func GroupNameLT(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldLT(FieldGroupName, v))
}

// GroupNameLTE applies the LTE predicate on the "group_name" field.
func GroupNameLTE(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldLTE(FieldGroupName, v))
}

// GroupNameContains applies the Contains predicate on the "group_name" field.
func GroupNameContains(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldContains(FieldGroupName, v))
}

// GroupNameHasPrefix applies the HasPrefix predicate on the "group_name" field.
func GroupNameHasPrefix(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldHasPrefix(FieldGroupName, v))
}

// GroupNameHasSuffix applies the HasSuffix predicate on the "group_name" field.
func GroupNameHasSuffix(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldHasSuffix(FieldGroupName, v))
}

// GroupNameEqualFold applies the EqualFold predicate on the "group_name" field.
func GroupNameEqualFold(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldEqualFold(FieldGroupName, v))
}

// GroupNameContainsFold applies the ContainsFold predicate on the "group_name" field.
func GroupNameContainsFold(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldContainsFold(FieldGroupName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldContainsFold(FieldPlatform, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.FieldLTE(FieldCreatedAt, v))
}

// HasPurchase applies the HasEdge predicate on the "purchase" edge.
func HasPurchase() predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PurchaseTable, PurchaseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPurchaseWith applies the HasEdge predicate on the "purchase" edge with a given conditions (other predicates).
func HasPurchaseWith(preds ...predicate.SubscriptionPurchase) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(func(s *sql.Selector) {
		step := newPurchaseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionPurchaseGroup) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionPurchaseGroup) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionPurchaseGroup) predicate.SubscriptionPurchaseGroup {
	return predicate.SubscriptionPurchaseGroup(sql.NotPredicates(p))
}
